### ISSUE TITLE
requirement for external subscriber to be able to choose what data-type (geojson/bufr4) to receive

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#120]
## User story
As an external subscriber to a wis2box, I want to be able to subscribe to the wis2broker so that I can receive messages of data being published for a specific data-type (currently bufr4 and geojson is published under the same topic)

## Acceptance criteria
- working example of subscribing to a specific data-type (geojson/bufr4)

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by petersilva** [comment]
One objection:  the relPath is supposed to represent the relative path of the file within the WAF.  if we add representation, then we add per file type directory layer everywhere.  and the pattern   grib/filename.grib  will show up everywhere. which seems a bit redundant.

The topic is supposed to represent the folder, and not the filename.  Filename was explicitly dropped from the topic tree.   This might have been a practical consideration based on AMQP limitation of field length to 255 characters, and a similar limitation in mqttv3 (don't recall the limit there) I think in mqttv5 the length of fields is practically unlimited... so not a constraint if we explicitly drop AMQP forever (not advocating, just describing the result of such a change.)

**Comment by maaikelimper** [comment]
closing, wis2box only publishes bufr nowadays ...
