### ISSUE TITLE
add support for monitoring capabilities

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2box#125]
## User story
As a wis2node operator, I need to monitor 
1. the services provided by the wis2node to be able to intervene in case a service has an issue
2. the incoming data in terms of the number of data from the configured data sources (stations or processes) and compare with an expected baseline. I need to be able to communicate to relevant teams issues regarding the decrease in incoming data or gaps with the baseline.
3. the workflow inside the wis2box. I need to be able to identify errors in the processing chain and reproduce them so that I can involve the relevant team for fixes.
4. tracking of metrics of data processing (passes, failures, logs)

## Acceptance criteria

- [ ] acceptance criteria 1
- [ ] acceptance criteria 2
- [ ] acceptance criteria 3

## Definition of done
- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by tomkralidis** [comment]
From meeting 2022-03-10:

Types of monitoring:
- service/healthcheck monitoring (uptime/behaviour)
  - WAF
  - MQTT
  - API
- internal wis2box workflow
 - status of incoming data (number of messages)
 - state of publishing
 - absolute counts as first pass (can deal with KPIs in later phase)

**Comment by tomkralidis** [comment]
Initial capability implemented in #168 -- thanks @maaikelimper !
