### ISSUE TITLE
Support ARM64 architecture

### ISSUE THREAD

**Issue by webb-ben** [wmo-im/wis2box#126]
## User story
As a wis2box user, I want wis2box images to offer at least amd64 and arm64 architectures [(or more)](https://www.winters.nz/docker/cross-platform-github-actions/)so that I can run wis2box on an ARM computer, like a raspberry pi. This is true for [pygeoapi](https://hub.docker.com/r/geopython/pygeoapi/tags), [wis2box-ui](https://github.com/wmo-im/wis2box-ui/pkgs/container/wis2box-ui), and [data-consumer/sarracenia](https://github.com/MetPX/sarracenia/pkgs/container/sarracenia_x64). @petersilva has added images tags with different architectures for sr3. I think that different architectures can be offered under the same tag using QEMU and docker buildx with Github Actions.

![image](https://user-images.githubusercontent.com/40066515/156362133-aeb664b8-1ebc-42d9-8740-75da2db497fc.png)

## Acceptance criteria

- [ ] all image wis2box uses offer multiple architecture support under one tag
- [ ] multiple architecture support included in ghcr build action

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by petersilva** [comment]
dup of #72 ... we should close one... I can close the other one... whatever people want.

**Comment by tomkralidis** [comment]
Suggest closing this one in lieu of #72, given there is already a trail there.
