### ISSUE TITLE
move default data pipeline to plugin

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#135]
Move the default data pipeline (`wis2box.data.observations`) out of wis2box to an external plugin (https://github.com/wmo-cop/wis2box-malawi-observations) to ensure separation of concerns.

**Comment by efucile** [comment]
I don't think we should have Malawi in the name.

**Comment by tomkralidis** [comment]
Malawi removed from templates and example plugins.

**Comment by tomkralidis** [comment]
- default data pipeline updated to be more generic
- external plugin example renamed to https://github.com/wmo-cop/wis2box-csv-observations
- plugin capability maintained
