### ISSUE TITLE
add more sarra documentation

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#136]
Add more documentation related to sarracenia:

- how to see a list of external brokers
- how to select a broker
- how to filter on 1..n topics
- how to enable/disable connection to brokers

**Comment by tomkralidis** [comment]
- website now available for sr3 docs in development/review
- uses Sphinx
- docs (alot of them!) need review

**Comment by petersilva** [comment]
new web page for documentation for version in wis2box: https://metpx.github.io/sarracenia/
