### ISSUE TITLE
Subscription and data access

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2box#14]
## User story
As a data user, I want to subscribe to a stream published by a node so that I will receive the data for which I subscribed on a specified filesystem/folder.

## Acceptance criteria
- [x] user is able to subscribe by entering the coordinates (and eventually password) of a broker and the topic in a configuration file
- [ ] user does not have to keep a process up and running to get the data. 
- [ ] brokers and topics need to be discoverable. This is part of another user story.

## Definition of done
- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by tomkralidis** [comment]
Adding to sprint-007 (cc @antje-s)
