### ISSUE TITLE
SSL everywhere

### ISSUE THREAD

**Issue by petersilva** [wmo-im/wis2box#140]
Need to configure every container that runs a service to use the SSL certificate (involves ensuring the certificates are in the right places for each one.  Services to configure so far:

* nginx
* mosquitto
* wis2box stack itself? or inherit from nginx?
* webdav

Since certificates have pretty short lifetimes (max 1 year) these days, need to arrange for auto-renewal, and automated replacement of certs, and restarting of the services using them.

implementing something like Lets Encrypt, with auto updating would be desirable.
Some countries nations may have security standards that conflict with use of external or specific SSL providers. so this part may need to be pluggable.

**Comment by tomkralidis** [comment]
@webb-ben sure.  We can also generate the certs and mount them across nginx and mosquitto.

**Comment by maaikelimper** [comment]
additional service to use SSL: grafana for the monitoring

**Comment by tomkralidis** [comment]
- nginx as proxy for other services
- nginx does SSL
- SSL is installed once on web proxy
- internal services are raw HTTP
- cert options
  - self-signed
  - letsencrypt (needs public facing address, hard for development)
  - commercial (i.e. Entrust)
- nginx configuration: http://nginx.org/en/docs/http/configuring_https_servers.html
 - we would put files where nginx wants them
 - keys needs to be created BEFORE docker-compose orchestration
 - have different nginx configs
  - unsecure (CI, dev.)
    - 80
    - 1883
  - secure (`docker/nginx/nginx.ssl.conf`)
    - 443
    - 8883
  - change `docker/docker-compose.yml` to point to `nginx.ssl.conf` and uncomment/edit volume map to .key and .crt
- we can have a build step to copy the `nginx.dev.conf` or `nginx.ssl.conf` to `nginx.conf`
- we need an SSL page/documentation
  - how to enable SSL
  - change env vars
  - startup

**Comment by tomkralidis** [comment]
cc @maaikelimper 

- option to enable/disable SSL, when SSL is disabled user should get clear warning on `wis2box-ctl.py` to indicate that this is for development only and production-environment requires HTTPS/MQTTS to be enabled
- prepare nginx/mqtt configuration files with/without SSL
- new environment variables to define `WIS2BOX_SSL_ENABLED` (`true`/`false`) and `WIS2BOX_NGINX_CERTS_DIR`, `WIS2BOX_MQTTS_CERTS_DIR` on local host for nginx and mqtt (and optionally sftp)

**Comment by golfvert** [comment]
Have you considered using traefik? As a proxy HTTPS/MQTTS/... it also makes autorenewal with let's encrypt fairly straightforward. 
MF Global Broker is using this setup.

**Comment by tomkralidis** [comment]
PR in #403; I will review today/tomorrow.

**Comment by tomkralidis** [comment]
Implemented in #403.
