### ISSUE TITLE
Import ISO19115 metadata

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/wis2box#143]
## User story
As a someone providing data through another system and publishing ISO19115 metadata, I want to convert my metadata to that used by the WIS2.0 box so that users can also the data through the box.

## Acceptance criteria

- [ ] Conversion tool to convert iso19115 metadata to yml format used by the WIS2box.
- [ ] Example metadata converted and available through box.

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by tomkralidis** [comment]
FYI import workflow implemented in pygeometa (https://github.com/geopython/pygeometa/pull/160).

Given pygeometa is install as part of the wis2box container, the user can use pygeometa directly.  Example:

```bash
pygeometa metadata import /path/to/19115.xml --schema iso19139
```

@david-i-berry can you test and provide feedback (pygeometa master is required)?  Once the import workflow is satisfactory, we can build deeper into the wis2box CLI and update the docs.

**Comment by tomkralidis** [comment]
To discuss with @david-i-berry on high level community requirements/workflow.  Need to clarify.
