### ISSUE TITLE
add CNAMES for wis2box

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#147]
As discussed, setup CNAMEs for:

- `wis2box.wmo.int` -> for now, point to https://community.wmo.int/activity-areas/wis/wis2-implementation
- `docs.wis2box.wmo.int` -> CNAME should point to `readthedocs.io` (I will complete domain configuration on RTD once CNAME is there).

**Comment by maaikelimper** [comment]
We need to agree with Enrico which URL's we are OK to use for wis2box

**Comment by tomkralidis** [comment]
@maaikelimper: as discussed with @efucile, let's start with:

- demo.wis2box.wmo.int: point to IP of physical box
- docs.wis2box.wmo.int -> CNAME should point to readthedocs.io (I will complete domain configuration on RTD once the CNAME is there)

**Comment by kurt-hectic** [comment]
@tomkralidis we generally try to avoid creating subdomains for the purpose of creating URL shortcuts. wis2box.readthedocs.io (or similar) are good enough to stand on their own (and should be recognized by the community better than a wmo subdomain). 
Along the same lines, subdomains are generally not created as shortcuts of (admittedly long) URLs of the community pages.

**Comment by maaikelimper** [comment]
Timo proposed to use wis2box-demo.wis.wmo.int to point to the IP of physical box . Any objections to this ?

**Comment by golfvert** [comment]
If I am being a bit pedantic, sorry, the subdomain is `wis2box.wmo.int` and `demo`, `docs` are hosts in that subdomain.
I guess one day we will have `www.wis2box.wmo.int` as a shiny web portal to explain what is wis2 in a box. So, grouping all sites docs, demo, www... under a unique (sub)domain is part of a typical setup for a web presence.
So, creating those CNAME would be a good thing for me...

**Comment by golfvert** [comment]
@maaikelimper I posted while you put your own comment. I would (strongly) prefer having all sites within the same (sub)domain.

**Comment by tomkralidis** [comment]
Updated URLs:
- demo.wis2box.wis.wmo.int
- docs.wis2box.wis.wmo.int

- www will be done at a later date (needs content/marketing)

**Comment by kurt-hectic** [comment]
We've discussed the request with the communications team and they are happy. DNS changes underneath wis2box.wis.wmo.int will be implemented next week.
Will have to work together about ssl certificates. From our side we need one for docs. Is the box ssl capable? Could think about a * certificate for box

**Comment by tomkralidis** [comment]
Docs is now live: https://docs.wis2box.wis.wmo.int

**Comment by tomkralidis** [comment]
demo
