### ISSUE TITLE
add installation by VM instructions

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#148]
Per discussion/presentation with @golfvert, add documentation for installing wis2box by way of VM (Proxmox).

**Comment by Maixentkambi** [comment]
is it possible to have a tutorial on the installation of this application?

**Comment by tomkralidis** [comment]
@Maixentkambi for wis2box itself, please see the quickstart in the documentation: https://wis2box.readthedocs.org.  Let us know if this helps. Note that this documentation would follow the actual VM installation.

**Comment by Maixentkambi** [comment]
I am trying to install the application on centos 7 of my desktop pc.
the document is not explicit on the installation part.
  what is the difference between wis2box-main and wis2box?

**Comment by golfvert** [comment]
I guess you are referring to the two installation methods described on the page
It is either the "ZIP Archive" method or the "Github" method.
Install git and use that one.
As, eventually, you may contribute to the code, git gets you a step closer.
If not already available here is how to install git https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by Maixentkambi** [comment]
Hi all,

I need a tutorial that explains step by step the installation of wis2box . The wis2box 0.2.dev0 documentation on this link https://wis2box.readthedocs.io/en/latest/ is not explicit.
Thanks

**Comment by Maixentkambi** [comment]
Hi all,
I am trying to run python3 wis2box-ctl.py start .
Here is the output

[root@localhost wis2box]# python3 wis2box-ctl.py start
Pulling prometheus (prom/prometheus:)...
Trying to pull repository docker.io/prom/prometheus ... 
latest: Pulling from docker.io/prom/prometheus
50e8d59317eb: Pull complete
67b9ebd12ea0: Pull complete
5b820e7f5505: Pull complete
fb3b0dac4e8e: Pull complete
354791b09254: Pull complete
862d5e05e31f: Pull complete
1570b941285f: Pull complete
997f7a5a88e9: Pull complete
1af9d2885e80: Pull complete
22d363a91b41: Pull complete
6b2479e05be0: Pull complete
c086c44eff40: Pull complete
Digest: sha256:2acfab1966f0dbecc6afbead13eca7f47062cfe8726bb9db25e39e0c0b88e9c3
Status: Downloaded newer image for docker.io/prom/prometheus:latest
Building metrics_collector
unknown flag: --iidfile
See 'docker build --help'.
ERROR: Service 'metrics_collector' failed to build : Build failed
[root@localhost wis2box]#

**Comment by tomkralidis** [comment]
Update 2022-10-28: consensus that guide should articulate that user starts from installing OS (recommend latest stable Ubuntu) and wis2box.
