### ISSUE TITLE
add discovery metadata editor UI

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#154]
## User story
As an operator, I want to have access to a user interface to manage discovery metadata, so that I can create discovery metadata using a web-based editor/wizard.

## Acceptance criteria

- [ ] wis2box-ui contains a view with a WCMP2 editor
- [ ] user can publish discovery metadata to the wis2box API / catalogue

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by golfvert** [comment]
I agree!
If we consider this as an "external" component of wis2box, this is something that can be used independently. So, a ready to use containerised webapp?
We will need "glue" between this and wis2box for the "publish" part. So, "import" the record in the wis2box, "publish" availability. Or something like that.

**Comment by tomkralidis** [comment]
As it happens, [ISRIC](https://www.isric.org) has been working on a metadata UI which works off a metadata schema to dynamically create a UI/UX.  This is very powerful for validation and generation of any metadata.  Excellent work here by @pvgenuchten.

We have since repackaged the project as part of the OSGeo ecosystem as mdme (Model Driven Metadata Editor).  https://github.com/OSGeo/mdme, which we can use in wis2box in support of WCMP2.  Load/validate/save workflow will work in conjunction with wis2box-api (pygeoapi API transaction endpoint).

**Comment by tomkralidis** [comment]
Update:
- discovery metadata UI editor will be built for wis2box integration as well as standalone mode (to allow for wider use)
- UI will talk to API (@tomkralidis) for workflow:
  - load
  - validate
  - save
  - delete
  - update

**Comment by tomkralidis** [comment]
A WCMP2 schema bundle is now available from https://github.com/wmo-im/wcmp2/blob/fix-schema/wcmp2-bundled.json

**Comment by tomkralidis** [comment]
2 modes:
- integrated (with API workflow for validation/transactions)
 - add topic hierarchy validation and record validation to wis2box-api
- standalone
  - copy/paste output

Auth:
- use wis2box-auth for now
- open new issue on upgrading auth to use something like Keycloak

Topic hierarchy:
- https://github.com/wmo-im/wis2-topic-hierarchy
- pywcmp implements [topic hierarchy bundle creation and validation](https://github.com/wmo-im/pywcmp)

**Comment by tomkralidis** [comment]
@sabers: should be ready today with local tests.

**Comment by tomkralidis** [comment]
- working meeting 2023-03-06
- updates made to Synoptic fork
- next working meeting on 2023-03-13 to test workflow with API

**Comment by tomkralidis** [comment]
- working on wis2box-ui-admin into wis2box docker compose setup
- Vuetify based on Vue 2
- need upgrade path for long term sustainability

**Comment by webb-ben** [comment]
wis2box-ui-admin uses Vue 2 because it is required by vjsf not by Vuetify. For instance, wis2box-ui uses Vuetify with Vue 3

**Comment by tomkralidis** [comment]
First pass implemented in wis2box-ui-admin in experimental mode.
