### ISSUE TITLE
bad data crashes wis2box

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#155]
wis2box needs to deal with bad data for input files. The following encoding errors occurred when wis2box was processing this file:
[WIGOS_0-454-2-AWSMAKANJIRA_2022-03-31T0755.csv](https://github.com/wmo-im/wis2box/files/8388889/WIGOS_0-454-2-AWSMAKANJIRA_2022-03-31T0755.csv)

ECCODES ERROR   :  Cannot encode 3HourPressureChange=46151.9 (subset=1)
ECCODES ERROR   :  encode_double_value: 3HourPressureChange. Value (46151.9) out of range (minAllowed=-5000, maxAllowed=5230).

which led to the warning:
2022-03-31 07:57:22,091 [WARNING] 14 wis2box.data.base publish Empty data for bufr4; not publishing

and which in turn led the sr3 process for data-ingest to crash **after which the wis2box stopped processing any new incoming files:**
FileNotFoundError: [Errno 2] No such file or directory: '/data/wis2box/data/public/2022-03-31/wis/data/core/observations-surface-land/mw/FWCL/landFixed/WIGOS_0-454-2-AWSMAKANJIRA_20220331T075500.bufr4'
    os.stat(filepath_out)
  File "/usr/local/lib/python3.8/dist-packages/wis2box-0.0.1-py3.8.egg/wis2box/event/data_ingest.py", line 56, in after_accept
    p(self.worklist)
  File "/usr/local/lib/python3.8/dist-packages/sarracenia/flow/__init__.py", line 223, in _runCallbacksWorklist
    self._runCallbacksWorklist('after_accept')

**Comment by tomkralidis** [comment]
@maaikelimper is this still an issue?
