### ISSUE TITLE
Release 0.1.0 broken by dependencies

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/wis2box#161]
- Division by zero error now raised by sr3.
- File not found error in csv2bufr due to change in mapping file name.

More details to follow.

**Comment by petersilva** [comment]
a number of div/0 errors have been fixed in later versions... the errors were introduced whan adding metrics to the logging to add average transfer rates.

**Comment by david-i-berry** [comment]
I'm not sure of best practice when it comes to importing external modules and libraries, Do we want to specify a version for the dependencies in the Dockerfile and requirements.txt files? At the moment we are using latest which can result in a working release becoming broken as is now the case for Release 0.1.0 of WIS2box.

**Comment by petersilva** [comment]
explanation of why the dependency broke
-------------------------------------------------------

Sarracenia changed the strategy for how dependencies are handled, allowing people to install what they need for a given deployment case.  prior to this change:  pip install metpx-sr3 would install all possible dependencies, for example pulling in dateparser, which itself triggers a dozen or so other packages to be downloaded, but is only used when polling an ftp server, so not used by the current configuration.  The pip packaging was changed to modularize functionality as "extras".  So one can make more compact distributions, and it is also much easier to create OS packages, this is part of stabilisation work for a release.  As of 3.0.15:
```

pip install metpx-sr3   - installs core only.
pip install metpx-sr3[mqtt]   - installs core + mqtt support.
pip install metpx-sr3[amqp,vip]   - installs core + support for high availability failover using vip.s
pip install metpx-sr3[ftppoll]  - adds support for ftppolling (requires dateparser)
```

2nd factor: docker image generation has been moved off of the metpx-sr3 onto a release branch, so it should cut down on the noise considerably.

**Comment by petersilva** [comment]
The dockerfile just had to explicitly install the extras going forward.

**Comment by petersilva** [comment]
@webb-ben does this make sense?

**Comment by webb-ben** [comment]
Agree it makes sense to only include dependencies as they are needed. 

However we decide to handle version control, I think it makes sense to ensure that the dependencies are on the same version across the box. For sr3 that is going to be using the same version of pip/git archive in the wis2box Dockerfile as the docker image used for all of the other sr3 containers. 

@petersilva in the #159 is still using v3.00.14 (https://github.com/wmo-im/wis2box/pull/159/commits/d3c354b8c8a3d6749464f912d8bb03acbd3a29ea)

**Comment by petersilva** [comment]
Tom pinned the version in that branch... I had added the missing dép... It wasn't necessary to pin although people can.
Fixing the dép fixes the current issue

**Comment by tomkralidis** [comment]
This has been fixed by #163.  @david-i-berry can you confirm/validate?

**Comment by webb-ben** [comment]
I am not sure the changes will be reflected in 0.1.0... Because 0.1.0 builds from the most recent zip archive of sr3 and csv2bufr. I believe would need to tag specific versions of these for 0.1.0 to work?

**Comment by david-i-berry** [comment]
It's the pinning to :latest that causes the problems and that can introduce breaking changes when a dependency changes. This came about as i was trying to role back to the 0.1.0 release of the WIS2box but couldn't due to changes to both sr3 and csv2bufr.

For future the releases do we want to pin to version numbers?

**Comment by tomkralidis** [comment]
We will definitely need to pin to sr3 and csv2bufr for the next release.

**Comment by tomkralidis** [comment]
Since fixed via pinning csv2bufr, bufr2geojson, wis2box-api and wis2box-ui on wis2box release (documented at https://github.com/wmo-im/wis2box/wiki/ReleaseManagement)
