### ISSUE TITLE
flexible plugin configuration

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/wis2box#164]
## User story
As a wis2box admin, I want to configure my box / plugin to be able to process multiple csv file layouts/formats without needing to write a new plugin for each format so that management of the box is easier.

## Acceptance criteria

- [x] wis2box plugin can process multiple csv file formats without needing a separate plugin for each
- [x] template specification is simple and can  be included in the mapping yml file

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by tomkralidis** [comment]
@david-i-berry I think we can close given the updates to the data mappings configuration?

**Comment by david-i-berry** [comment]
Addressed in release 2.0 and decoupling of BUFR and geojsons.
