### ISSUE TITLE
Data persistence in one node

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2box#17]
## User story
As a data user, I want to be able to access data up to n-days data old so that I will be able to visualise or download n-days of data.

## Acceptance criteria

- [x] data user is able to access and download data up to n-days old
- [x] n-days to be configure by the node manager

## Definition of done

- [ ] unit/functional tests added/updated
- [x] documentation updated
- [ ] live demonstration provided

**Comment by efucile** [comment]
after n-days the data are sent to and archive service (to be defined) and deleted from the node

**Comment by tomkralidis** [comment]
Implemented via `WIS2BOX_DATA_RETENTION_DAYS` (docs at https://wmo-im.github.io/wis2box/running/data-retention.html)
