### ISSUE TITLE
add specific Python and Docker installation instructions to docs

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#176]
In the documentation, we specify minimum Python and Docker versions, but it would be valuable to further specify (how to install on given operating systems, etc.) as part of the requirements and dependencies section of the [installation](https://docs.wis2box.io/en/latest/installation.html#requirements-and-dependencies) page.

Ref: https://github.com/wmo-im/wis2box/discussions/2#discussioncomment-2681189

**Comment by maaikelimper** [comment]
Hi Tom, in regards to this I wanted to point out that the documentation currently says:
wis2box requires [Python](https://www.python.org/downloads) 3 and [Docker](https://docs.docker.com/get-docker) 1.13+

I'm actually using Docker Docker version 20.10.12, which seems like a big difference and (see discussions) [Maixentkambi](https://github.com/Maixentkambi) is using Docker 1.13 which I thought was the reason why the installation of wis2box failed for this user.

I propose we align the instructions in the docs to match the docker-version used in the github-action so we are sure the version quoted in the docs has been tested to work.

**Comment by Maixentkambi** [comment]
Hi all,
I could install wis2box when I updated my docker. Currently I am using version 20.10.15

**Comment by tomkralidis** [comment]
Note that the documentation has now been updated in https://wis2box.readthedocs.io/en/latest/installation.html#requirements-and-dependencies
