### ISSUE TITLE
set MQTT QoS in mosquitto

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#184]
## User story
As a wis2box operator, I would like to set the MQTT QoS capability so as to guarantee message delivery attempts ([background info](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels)).

## Acceptance criteria

- MQTT endpoint is provisioned with QoS=1

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by petersilva** [comment]
It's always 1... selected as standard... you have no possibility to pick any other QoS.

**Comment by petersilva** [comment]
not quite true... it can be overridden if desire... but one should not change that setting. It is always 1.
