### ISSUE TITLE
Alignment of wis2box with WIS2 tech specs

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2box#187]
## User story
As a WIS2 in a box project manager, I want wis2box to be a reference implementation of a WIS2 node so that NCs and DCPCs will implement WIS2 correctly. It is not a good practice to provide alternative solutions that are not in the technical specifications to implement in a reference implementation. Example: Sarracenia is offering many solutions that were ruled out from the WIS2 tech specs like AMQP and suggested ways of replicating trees similar to rsync. It is suggested to remove Sarracenia from wis2box and replace it with simple python forcing the user to implement only WIS2 tech specs. 

## Acceptance criteria

- [x] Sarracenia is not part of wis2box
- [ ] an operator can configure wis2box to share data through MQTT according to the WIS2 topic structure and message schema
- [ ] an operator can configure wis2box to subscribe to a Global Broker 
- [ ] an operator can configure wis2box to download data of interest through MQTT notifications applying client-side filtering
- [x] events internal to the box are handled using an MQTT broker with a minimal extra layer of software
- [ ] further analysis of wis2box does not present other similar issues

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by golfvert** [comment]
Acceptance criteria #3 should read, I think:

- [ ] an operator can configure wis2box to subscribe to a Global Broker

No direct subscription to another node. Strictly saying technically this won't make a difference. Both will run MQTT brokers... However, it is important to specify it according to the agreed architecture.

**Comment by efucile** [comment]
> Acceptance criteria #3 should read, I think:
> 
> * [ ]  an operator can configure wis2box to subscribe to a Global Broker
> 
> No direct subscription to another node. Strictly saying technically this won't make a difference. Both will run MQTT brokers... However, it is important to specify it according to the agreed architecture.

Acceptance criteria have been modified accordingly.

**Comment by tomkralidis** [comment]
Depends on #200
