### ISSUE TITLE
investigate aria2 for download functionality

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#200]
Investigate [aria2](https://aria2.github.io) as an option to support subscribe/download functionality in wis2box.

cc @golfvert

**Comment by antje-s** [comment]
Can I combine aria2 with
threading and urllib3.PoolManager() ?
The download script uses both.

**Comment by antje-s** [comment]
Or is it used as a command line command (analogous to e.g. wget)? Then we would have to create a list upstream in the py script that performs the checks (duplicate / whilelist check), which we pass as a bundle to the command line tool to achieve a performance gain, right?

**Comment by golfvert** [comment]
As I have proposed this, I may comment on this issue. aria2c has a JSON RPC interface. Considering the overall architecture, I am thinking having aria2c in seperate container(s). The "downloader" function in WIS2 in a box would have to use the JSON RPC interface to request download, get updates on those,... The way I see it, using aria2c would allow using all protocols that we want (today SFTP, HTTP(S), tomorrow torrent?) is a standard manner. So, it is not about using the CLI but the JSON RPC interface. See https://aria2.github.io/manual/en/html/aria2c.html#rpc-interface

**Comment by golfvert** [comment]
If the people who know something about software development (hence, not me...) consider it is not the "right" thing (for whatever reason), no problem with me :)
Last point ,  using (or consider using) off the shelf solution is also consistent with WIS2 approach.

**Comment by tomkralidis** [comment]
How composable is aria2?  Consider the use case of downloading from a broker subscription/notification:

- client subscribes to broker
- broker sends notification message
- client parses notification message for `rel=canonical` link
- client downloads link locally

**Comment by golfvert** [comment]
Not sure what "composable" means here...

From the manual:

```
JSON-RPC Example

The following example adds http://example.org/file:

import urllib2, json

jsonreq = json.dumps({'jsonrpc':'2.0', 'id':'qwer',

                      'method':'aria2.addUri',

                      'params':[['http://example.org/file']]})

c = urllib2.urlopen('http://localhost:6800/jsonrpc', jsonreq)

c.read()
'{"id":"qwer","jsonrpc":"2.0","result":"2089b05ecca3d829"}'

```

So in our use case, the "http://example.org/file" is the links from the message.

**Comment by antje-s** [comment]
JSON-RPC sounds interesting...running as a service in the background so that we can pass url for download to it. Connection pool management, threading etc. would then be moved to aria2. Further development and updates through the aria2 community...would be good.

How do you know if a download has failed? Is there a monitoring UI or do you have to monitor the aria2-log?

**Comment by golfvert** [comment]
Through the websocket interface, it is possible to receive notifications of events. See https://aria2.github.io/manual/en/html/aria2c.html#json-rpc-over-websocket
Events are sent on eg. onDownloadComplete and onDownloadError.

It is also possible to monitor the active download using the same interface (tellStatus...).
To me, the list of methods to control/monitor/add/delete/... download is quite comprehensive.

It is also possible, for example, to reorder downloads, should we need this to manage priorities.

**Comment by tomkralidis** [comment]
Notes:
- add aria2 container (not sure if this exists from aria2 proper or whether we need to build our own Docker setup
- subscribe/download workflow would:
  - subscribe to the broker
  - on notification
    - parse message
    - download to local storage using aria2 container via XML-RPC or JSON-RPC

**Comment by golfvert** [comment]
For my tests I have used this container: https://hub.docker.com/r/p3terx/aria2-pro
It is updated regularly. It works fine...

**Comment by tomkralidis** [comment]
Consensus is core workflow does not require aria2.  Having said this, @antje-s's work in pywis-pubsub contains an optional capability for aria2 if desired.
