### ISSUE TITLE
add BUFR pipeline

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#208]
## User story
As a data producer, I want to publish my existing BUFR data so that conformant BUFR data (that is produced upstream of wis2box) can be published to WIS 2.

## Acceptance criteria

- [x] WSI check and validation, add if required
- [x] separation of messages / subsets
- [x] location/time validation

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by david-i-berry** [comment]
### Separation of messages / subsets:

See https://github.com/wmo-im/bufr2geojson/blob/c7d8ffce8ad10a8e4951b4f5b598b9eaeb94b478/bufr2geojson/__init__.py#L790

and 

https://github.com/wmo-im/bufr2geojson/blob/c7d8ffce8ad10a8e4951b4f5b598b9eaeb94b478/bufr2geojson/__init__.py#L807

to 

https://github.com/wmo-im/bufr2geojson/blob/c7d8ffce8ad10a8e4951b4f5b598b9eaeb94b478/bufr2geojson/__init__.py#L810

It should be possible to write out the individual subsets using `codes_write()`.  See

https://github.com/wmo-im/csv2bufr/blob/75844b40970f7d7dfe95f0a09b2eca4d9299b98a/csv2bufr/__init__.py#L435

for example of call.

**Comment by david-i-berry** [comment]
### Location / time validation and WSI validation

It might be easiest to use the bufr2geojson for this and then check in the resulting GeoJSON. 

I'll have a look at how to add the extra WSI sequence, this will be based on:
 https://confluence.ecmwf.int/display/UDOC/How+do+I+add+WIGOS+station+identifiers+to+a+BUFR+message+-+ecCodes+BUFR+FAQ.

**Comment by tomkralidis** [comment]
Sequence:
- check for WSI in actual data/content, else:
- check for WSI in filename, else:
- attempt to match via lookup
  - support design time config, mapping WMO ID/block number/station number to WSI
- else: throw error

We should also have test data to help validate and tests for regressions based on common cases.

**Comment by david-i-berry** [comment]
I would warn rather than throw error. Some marine stations report anonymously (due to security and / or commercial concerns). For these we will not be able to lookup or create a WSI otherwise the above looks good.

**Comment by tomkralidis** [comment]
- Update: need to add data for different test cases (multiple subsets)
- Italy/Algeria test data should exemplify multiple subsets that we can test

**Comment by efucile** [comment]
Some considerations on implementing a degree of control in the data exchanged by the wis2box with a BUFR pipeline.
Two extreme options
1. I can send any data in the box from any country, and they will be exchanged. This is a very permissive way that does not safeguard against erroneous exchange of data. I mean, if I am NC Italy, I should exchange only Italian data, and if I send data from another country in a box, I should get an error. I should get an error in general if the data from a country are published on the topic of another country. I should also get an error if the data I am sending in the box is not supposed to be part of the international data exchange.
2. A configuration file in the wis2box provides a mapping between block/station number and WSI. Only data with block/station number or WSI in this file are exchanged. This will enable full control by the manager of the box on the data that are exchanged. It will require a significant effort as if the NC has hundreds or thousands of stations, the configuration file may require a script or some visual tool for management purposes.
Option 1. is currently implemented and is giving wide flexibility. Too much?
Option 2. is safer and more restrictive and would require significant maintenance work.
We need to decide which way to go.

**Comment by david-i-berry** [comment]
I am struggling to see the difficulty here. 

TSIs in use on the first July 2016 have all been mapped to a WSI and should be present in OSCAR. and we can search using either this WSI or the new WSI if one has been allocated. We can also create a mapping file from the data in OSCAR, for example like the one below. This takes less than 5 minutes to generate.

[wsi_map.csv](https://github.com/wmo-im/wis2box/files/9409077/wsi_map.csv)

**Comment by david-i-berry** [comment]
And the code used to generate the file (using R)

```R
library(jsonlite)
# Load WIGOS metadata
wigos_data <- fromJSON("https://oscar.wmo.int/surface/rest/api/search/station?programAffiliation=GOS")
wigos_data <- wigos_data$stationSearchResults

# now extract ids
idx <- seq(1, nrow(wigos_data))

process_wsi <- function(df_in){
  idx <- 1:nrow(df_in)
  primary <- which(df_in$primary)
  primary <- rep(df_in$wigosStationIdentifier[primary], nrow(df_in))
  res <- lapply(idx, FUN = function(X, the_data){
    words <- unlist(strsplit( the_data$wigosStationIdentifier[X],"-"))
    if(length(words) != 4){
      print("Bad WSI")
      print(the_data$wigosStationIdentifier[X])
      block = "bad"
      station = "bad"
    }else{
      if( words[2] == "20000"){ # we have block and station
        block <- substr(words[4],1,2)
        station <- substr(words[4],3,5) 
      }else{
        block <- NA
        station <- NA
      }
    }
    ret <- data.frame(block = block, station = station, 
                      wsi = the_data$wigosStationIdentifier[X])
  }, the_data = df_in)
  res <- do.call('rbind',res)
  res <- cbind(res, primary_wsi = primary)
  return(res)
}

wsi <- lapply( idx, FUN = function(X,the_data){
  wsi <- process_wsi(the_data[X,]$wigosStationIdentifier[[1]])
  territory <- the_data$territory[X]
  region <- the_data$region[X]
  station_name <- the_data$name[X]
  wsi <- cbind(wsi, territory = rep(territory, nrow(wsi)),
               region = rep(region, nrow(wsi)),
               name = rep(station_name, nrow(wsi)))
  return(wsi)
}, the_data = wigos_data)

wsi <- do.call('rbind',wsi)
write.table(wsi,row.names=FALSE,file = 'wsi_map.csv', sep = ',')

```

**Comment by efucile** [comment]
Not all the TSIs were in OSCAR at the time of conversion. Your csv file will be incomplete.

**Comment by webb-ben** [comment]
@efucile I think it is important to maintain the scope to which control is already exercised in wis2box. wis2box will only operate on files matching the configured [data-mappings](https://github.com/wmo-im/wis2box/blob/main/wis2box/resources/data-mappings.ym). For wis2box to process a file, the file must be placed inside a path of a valid topic, in a specific bucket, matching a file type and a file pattern. 

> I should get an error in general if the data from a country are published on the topic of another country. I mean, if I am NC Italy, I should exchange only Italian data, and if I send data from another country in a box, I should get an error. 

The Italian wis2box should not contain data mappings for anything other than the italian wis2box. It would be an error to configure the processing of data from other countries. We tell wis2box what countries it is responsible by telling it how to process data matching topic hierarchies of the country.  not an error in the way wis2box decides what it 

> I should also get an error if the data I am sending in the box is not supposed to be part of the international data exchange.

The aforementioned data-mappings also includes configuration for what data the notification should be sent for. It would be an error to configure a notification to be sent for data that is not a part of international data exchange.

**Comment by webb-ben** [comment]
With all of this in mind, #234 currently uses the [bufr2geojson parser](https://github.com/wmo-im/bufr2geojson/blob/694683e8838f768deb60e7477217b2ea6998bcc9/bufr2geojson/__init__.py#L416-L529) to derive WSI. This attempts to use the bufr: wigos identifiers OR block-num/station-num OR ship_or_mobile_land_station_identifier and the list goes on (credit to @david-i-berry). This means wis2box can approach all of these identifier sequences in a consistent fashion, using just the wsi as the common form of identifier. 

It would be very easy to modify the `station_list.csv` file to serve as some sort of lookup table. The content of which can be more than just the station name and wsi. I can start by making the station list static, such that the wsi's need to be provided preflight in order for wis2box to process

**Comment by tomkralidis** [comment]
2022-09-26: TODO: management workflow of `station_list.csv` (push to s3, etc.)

**Comment by tomkralidis** [comment]
Closing this issue as done.  Will continue station list management in sprint-007
