### ISSUE TITLE
refactor and streamline repository

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#213]
wis2box at present is built out as follows:
- wis2box: Python package with docker setup for entire stack
- wis2box-api: separate repository
- wis2box-ui: separate repository

To streamline development and better represent functionality:
- update wis2box repository into repo of docker components
 - `docker-compose*.yml` files at root
 - each component in its own top level directory (api, ui, auth, etc.)
- move wis2box-api and wis2box-ui proper as top level directories into wis2box repo

This will also help in cutting a single version against a single repo as part release management.

**Comment by webb-ben** [comment]
I like the idea of restructuring the repository to have component folders at the root level. 

For what its worth, I think wis2box-ui and wis2box-api are better left in separate repositories. Their respective directories could be compose file configuration for these images. It is my impression that including the source code for these components encumbers future modular growth. 

How is this going to work with nginx configuration? Will `python3 wis2box-ctl.py ...` still have zero dependencies to run on a fresh install of python3?

**Comment by tomkralidis** [comment]
Implemented in #362
