### ISSUE TITLE
provide public demo

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#239]
## User story
As a wis2box stakeholder, I want to have access to a public demo so that I can test and try out wis2box and evaluate its current functionality.

## Acceptance criteria

- [ ] provide demo at https://demo.wis2box.wis.wmo.int
- [ ] demo should be based on the latest wis2box source code (should we update hourly? Daily? On each commit?)
- [ ] any protected data should have access control applied

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by Jolik** [comment]
**We are waiting with great interest!**

**Comment by maaikelimper** [comment]
18.194.9.188 is now http://demo.wis2box.wis.wmo.int/ 
Some files are being forwarded from the DWD-GISC into the Italy topic. (Further debugging is needed)

**Comment by tomkralidis** [comment]
Can we enable HTTPS here?

**Comment by tomkralidis** [comment]
HTTPS enabled via https://demo.wis2box.wis.wmo.int
