### ISSUE TITLE
cronjob for wis2box data archive never runs

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#240]
I noted that the daily archive job on the future demo-wis2box has never runs (it's been up for 7 days) . If I run it manually from inside the wis2box-container it runs correctly.

**Comment by maaikelimper** [comment]
cron was not installed, fixed in minio-updates

**Comment by maaikelimper** [comment]
I still don't see files being archived on demo.wis2box.wis.wmo.int re-opening this until I can demonstrate that it is fixed

**Comment by tomkralidis** [comment]
Implemented in #275
