### ISSUE TITLE
improve topic hierarchy configuration process

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#246]
wis2box should make it easy for a user to send out their data on a topic structure that is compliant with 
https://github.com/wmo-im/wis2-topic-hierarchy/tree/hierarchy-not-on-readme/topic-hierarchy

the current implementation makes it really hard as:
- hierarchy is hardcoded in wis2box/resources/data_mappings.yml
- same hierarchy needs to be repeated in 'metadata discovery publish' and 'api add-collection' steps, increasing chance of issue due to typo
-  examples used in documentation and github-action use incorrect topic-structure
- documentation overall could be improved, I would recommend update quickstart to be a more generic quickstart-recipe rather than one relying on files already created

**Comment by tomkralidis** [comment]
Update: way forward will be implemented in wis2box-guide

**Comment by maaikelimper** [comment]
done, documentation was updated and metadata simplified.
