### ISSUE TITLE
remove leaflet attribution in wis2box-ui map

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#260]
remove leaflet attribution in wis2box-ui map, to avoid WMO not appearing neutral due to presence of Ukraian flag

ben can check how to do it

enrico can check if we should do it

**Comment by efucile** [comment]
this is an example of Leaflet attribution without flag http://demo.wis2box.wis.wmo.int/oapi/collections/mwi.malawi_wmo_demo.data.core.weather.surface-based-observations.SYNOP
we should do the same in the home page

**Comment by efucile** [comment]
My proposal is to leave the attribution and remove the flag

**Comment by maaikelimper** [comment]
deployed on all WMO-owned wis2box-instances, closing
