### ISSUE TITLE
provide data transformation pipeline

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#27]
For the initial phase, CSV2BUFR is the driving data transformation component.  Workflow:

- file arrives on disk (say `$WIS2NODE_DATADIR/incoming`)
- sarracenia watch config will trigger a CSV2BUFR process, passing the file/stream of CSV data
  - we need to determine the CSV2BUFR entrypoint (internal HTTP API process? As an OGC API - Processes process?)
- CSV2BUFR should contain all appropriate auxiliary files for run-time processing:
  - mappings/config
  - station metadata
    - NOTE: wis2node has WSI sync process from OSCAR/Surface, which caches (JSONs) of station metadata in `$WIS2NODE_DATADIR/metadata/station`)
- CSV2BUFR converts CSV to BUFR and saves to `$WIS2NODE_DATADIR/data/...` (subdirs to be defined)

The following are also required:
- update as a Python package and publish to PyPI
- tests/docs
- provide a Docker image

**Comment by david-i-berry** [comment]
More info on slack

https://wmo-cop.slack.com/archives/C02K2CZ3LP4/p1637085858001700

**Comment by tomkralidis** [comment]
Baseline capabilities were demonstrated at today's standup via CLI.  We need to work on pubsub as well as some minor tweaks.

**Comment by tomkralidis** [comment]
0.1.0 provides the baseline capability.
