### ISSUE TITLE
wis2box-ui map performance issues

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#278]
The map on the wis2box-UI becomes quite slow when a large number of stations has to be loaded. It looks like many individual API-calls are made to load the map. 
Would it be possible to improve the performance of the wis2box-UI by reducing the number of API-calls ? 

As demonstrated by wis2box-australia: http://3.124.208.185/

**Comment by tomkralidis** [comment]
Fixed as part of https://github.com/wmo-im/wis2box-api/pull/17 and https://github.com/wmo-im/wis2box-ui/pull/62
