### ISSUE TITLE
Performance issues wis2box-ui for stations-data with data over a long time-range

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#282]
Rory Burke and David Berry are working on updating data with a long time-range on "wis2box-daycli".

The UI for this wis2box is currently available at http://3.68.233.152:8080/

wis2box-daycli currently has only 2 stations and Rory is uploading data for a long time-range: 1932-2022, to enable climate-studies through the wis2box-api.

I note that the wis2box-UI for wis2box-daycli gets stuck loading data when opening the "data"-window for one station, and I can see a large number of network requests:
![image](https://user-images.githubusercontent.com/19169339/194281892-356c9215-3061-4bf6-b4da-ada81fd60183.png)

**Comment by tomkralidis** [comment]
@maaikelimper is this still an issue?

**Comment by maaikelimper** [comment]
no this was fixed with the various UI-improvements during the sprint
