### ISSUE TITLE
WIS2BOX_API_URL are not picked up in the wis2box-ui due to href-attribute stored in /oapi/collection/stations stores api_url

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#285]
Changes I've made to my WIS2BOX_API_URL are not picked up in the wis2box-ui.

For example I changed WIS2BOX_API_URL=https://demo.wis2box.wis.wmo.int/oapi and restarted the stack

First entry returned by https://demo.wis2box.wis.wmo.int/oapi/collections/stations/items?topic=mwi.malawi_wmo_demo.data.core.weather.surface-based-observations.SYNOP&f=json
contains
"links": [{"rel": "collection", "href": **"http://demo.wis2box.wis.wmo.int/oapi/collections/mwi.malawi_wmo_demo.data.core.weather.surface-based-observations.SYNOP"**, "type": "application/json", "title": "mwi.malawi_wmo_demo.data.core.weather.surface-based-observations.SYNOP"}]}

**Comment by tomkralidis** [comment]
Changes made to public facing environment variables (https://docs.wis2box.wis.wmo.int/en/latest/administration.html#public-environment-variables) require refresh of the station collection metadata.  Can you try running ` wis2box metadata station sync $WIS2BOX_DATADIR/metadata/station/station_list.csv`?
