### ISSUE TITLE
visualize station observations

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#29]
add the following capabilities to wis2node-ui:

- show map of stations, colour coded by reporting status
- click station and show a time series (default last 24 hours) graph
  - allow for user modification to temporal extent of graph
  - provide link to download time series

All interactions should happen via OGC API - Features

**Comment by webb-ben** [comment]
https://plotly.com/javascript/time-series/

**Comment by tomkralidis** [comment]
Punting to sprint-002 given we need to complete the data generation/publication to pygeoapi
