### ISSUE TITLE
create guide

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#296]
## User story
As a user deploying wis2box, I want a clear guide on installing and running wis2box, which provides focus on deployment(user type), I want to (task) so that (goal).

## Acceptance criteria

- [x] guide should be developed using Sphinx and rST
- [ ] guide should be hosted on Read The Docs via https://guide.wis2box.wis.wmo.int

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by tomkralidis** [comment]
- Initial scaffolding setup at https://github.com/wmo-im/wis2box-guide
- Configured via readthedocs at https://guide.wis2box.wis.wmo.int
  - ACTION: @maaikelimper @kurt-hectic do we need to add a CNAME from guide.wis2box.wis.wmo.int to `readthedocs.io` ?  Not sure if/how this was done for #147.  The domain is setup in RTD, but is pending validation
- next steps would be a table of contents before populating content

**Comment by maaikelimper** [comment]
- content of https://wis2box-user-guide.readthedocs.io to move into the documentation of wis2box-repository
- original content of documentation in wis2box-repository to move into separate chapter
- merge content of original with new 
- work in dedicated documentation-branch until Tom/Maaike agree on first version for Beta1
- share template with docs used for other repo's (csv2bufr etc.)

**Comment by tomkralidis** [comment]
Addressed via #349
