### ISSUE TITLE
add optional FTP setup

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#297]
## User story
As a wis2box user, I want wis2box to be able to accept data upload via FTP, so that I can upload my data in a lower barrier fashion.

## Acceptance criteria

- [ ] optional docker setup for FTP (ProFTPD)

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by maaikelimper** [comment]
I've added a separate repository for this feature here: https://github.com/wmo-im/minio-ftp-forwarder

I've tested this on the physical wis2box WMO has started to prepare for Zimbabwe

**Comment by maaikelimper** [comment]
add the option of using 'minio-ftp-forwarder' to our documentation describing data ingestion options

**Comment by tomkralidis** [comment]
@maaikelimper to add optional docker compose setup in `docker/`

**Comment by maaikelimper** [comment]
I need to do some more work to test and prepare standalone images and a docker-compose that reference environment variables from wis2box, to be bumped to sprint-009

**Comment by tomkralidis** [comment]
As an extra, I think we should document this in wis2box for optional FTP forwarding workflows, with steps on how to run wis2box-ftp. I don't think this needs to be supported by `wis2box-ctl.py` proper.

**Comment by tomkralidis** [comment]
Implemented in #409

**Comment by tomkralidis** [comment]
To test in a future iteration.
