### ISSUE TITLE
implement data storage directory structure

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#31]
Create a storage directory structure for wis2node to support the various data/files managed within an installation.

- data
  - local data processing
    - incoming
    - outgoing
  - downloaded data from other wis2node services
- metadata
  - discovery
  - station

**Comment by tomkralidis** [comment]
\+ @petersilva

Initial proposal to feed discussion:


```
|____data
| |____outgoing  # for publication
| |____public  # data available via PubSub and STAC
| | |____YYYY-MM-DD
| | | |____originating-centre
| | | | |____data-category
| | | | | |____dataset-name
| |____incoming  # incoming (CSV) data to be processed
|____metadata  # to feed API publication and OSCAR/Surface caching
| |____discovery
| |____station
```

**Comment by tomkralidis** [comment]
Based on discussions with @petersilva

Example structure: `/<RFC3339>/<source>/<ISO-3166-2>/<originating-centre>`

- `originating-centre`: https://github.com/wmo-im/GTStoWIS2/blob/main/GTStoWIS2/TableCCCC.json
- relative sarra path starts at `<source>`

**Comment by tomkralidis** [comment]
updated proposal:

```
|____data
| |____outgoing
| |____public
| | |____YYYY-MM-DD
| | | |____source
| | | | |____country-code
| | | | | |____originating-centre
| | | | | | |____data-category
| | | | | | | |____dataset-name
| |____incoming
|____metadata
| |____discovery
| |____station
```

**Comment by efucile** [comment]
my suggestion

|____data
| |____config
| |____outgoing
| |____public
| | |____YYYY-MM-DD
| | | |____source #please define source. Is it the an identifier for the broker?
| | | | |____tree type = land observations #different tree structure depending on land, ocean, satellite obs or other products
| | | | | |____country-code #ocean, satellite, NWP data don't have country-code
| | | | | | |____originating-centre
| | | | | | | |____data-category
| | | | | | | | |____dataset-name
| |____incoming
| | |____YYYY-MM-DD
| |____errors
| | |____YYYY-MM-DD
|____metadata
| |____discovery
| |____station

**Comment by tomkralidis** [comment]
- `/data/public/YYYY-MM-DD/source` would be a fixed value of `wis` here
- tree type: the thinking was that `data-category` would cover this?  Having said this
- country-code: perhaps we omit in lieu of originating-centre only?

Update (narrowed to `/data/public`):

```
| |____public
| | |____YYYY-MM-DD
| | | |____source
| | | | |____data-category/tree-type
| | | | | |____originating-centre
| | | | | | |____dataset-name
```

One issue would be that "data-category/tree-type" could potentially have varying levels of nesting.

cc @petersilva for comments/insight

**Comment by efucile** [comment]
The originating center is not a country. You may want to have a country level split and know who is generating the data

**Comment by tomkralidis** [comment]
Update based on discussion with ECMWF:

```
|____public
| |____YYYY-MM-DD
| | |____source
| | | |____tree-type
| | | | |____country-code
| | | | | |____originating-centre
| | | | | | |____data-category
```

Notes: the dataset-name (now removed) would be a composite of `tree-type.country-code.originating-centre.data-category`

**Comment by tomkralidis** [comment]
Update:

- there will varying levels of hierarchy based on the data category (observations, NWP, satellite, ocean, etc.)

Building with surface observations as critical path:

- `data_category.country_code.originating_centre.station_type.representation`

where:

- `data_category`: new codelist
- `country_code`: ISO 3166-2
- `originating_centre`: keys from https://github.com/wmo-im/GTStoWIS2/blob/main/GTStoWIS2/TableCCCC.json
- `station_type`: https://codes.wmo.int/wmdr/_FacilityType
- `representation`: new codelist

Example: `observations-surface-land.ca.cwao.landFixed.bufr`

**Comment by petersilva** [comment]
That looks really helpful, but it does not have complete coverag: station_type only mentions obs.  what about: nwp outputs, forecasts, synthetic satellite imagery? or text forecasts and warnings? Also, is RADAR landFixed?

**Comment by tomkralidis** [comment]
Good points @petersilva: land surface obs is our initial iteration. The tree will evolve as we build out NWP, forecast, satellite.

**Comment by petersilva** [comment]
If that is the hierarchy you want, then we can attempt to modify the tables in GTStoWIS2 to generate them for matching WMO386 AHL's. This is exactly the kind of feedback we have been trying to solicit to the proposed topic tree.

**Comment by petersilva** [comment]
In discussions in GTStoWIS (TT protocols team) we have agreed to omit file format (aka representation) as it was agreed that files should have, as is universal convention outside the weather world, appropriate file extensions.  As the topics correspond to file folders, having type in the topic (which is also a folder) will result in all files having the representation twice. e.g:

`
    a/b/type/c/filename.type
`

The file type/data representation will unavoidably show up twice. Ideally, one looks up some form of information, say alerts, and the directory offers .cap files, .geojson files, and  .crex files, and perhaps .txt ones. The committee considers the fact that data with different representations does not show up in the same directory currently to be a bug in our proposed topic tree.  One that we have issues open to address  ( e.g.: https://github.com/wmo-im/GTStoWIS2/issues/55, https://github.com/wmo-im/GTStoWIS2/issues/39  )

**Comment by tomkralidis** [comment]
Update standup 2021-12-03:

- HH: example for SYNOP, do we extend the tree
- DB: leave that for data inspection

- DB: for ocean, we can use regions as named geographies
- DB: collaborating networks are not originating centres, how do we include them as well?

- PM: how do we deal with lake buoy data on Lake Malawi?
- XC: what is the origin of https://github.com/wmo-im/GTStoWIS2/blob/main/GTStoWIS2/TableCCCC.json ?  Seems 2x bigger than from the GTS manual (@petersilva comment?)

- DB: `...public/YYYY-MM-DD`: is this the publish date or date of observation?  Should be the latter

- DB/XC: output data filename convention can be more indicative: TODO in csv2bufr

**Comment by david-i-berry** [comment]
For marine regions the high level geographies from https://www.marineregions.org/gazetteer.php?p=details&id=23616 may be useful.

**Comment by david-i-berry** [comment]
> * DB: collaborating networks are not originating centres, how do we include them as well?
> *

In terms of my comment, one of the big advantages of the WIS2.0 is that it opens up the system to observations from other communities. For example, if say an oceanographic data centre wanted to setup a WIS2.0 node and make data available via the node the proposed originating centre hierarchy may not be appropriate.

**Comment by tomkralidis** [comment]
Current state of directory structure (based on initial iteration of surface weather data):

```
|____data
| |____config
| |____outgoing
| |____public
| | |____YYYY-MM-DD
| | | |____source
| | | | |____tree-type
| | | | | |____country-code
| | | | | | |____originating-centre
| | | | | | | |____data-category
| |____incoming
| | |____YYYY-MM-DD
| |____errors
| | |____YYYY-MM-DD
|____metadata
| |____discovery
| |____station
```

Remaining points:
- file type as part of topic hierarchy (@petersilva / @efucile): based on TT-Protocols recommendation, we should not include the data representation as part of the tree per se
- collaborating networks are not always originating centres (@petersilva / @david-i-berry).  Should there be guidance on how non-originating centres can define themselves at this part of the tree?

**Comment by petersilva** [comment]
Table CCCC:  
* derivation of current table: https://github.com/wmo-im/GTStoWIS2/issues/4  
* suggesting further additions: https://github.com/wmo-im/GTStoWIS2/issues/43

**Comment by petersilva** [comment]
CCCC is just a GTS transition mechanism... The mapping being done by GTStoWIS2 module is to the "centre" field in the table, which is kind of simplified, lower-case but much more readable names.  "AMRF" -> "melbourne_regional_forecasting_centre"  ... This use of ascii constrained simplified place names, far more readable for most than the four letter CCCC's is invented as as part of and implicit in the GTStoWIS2 proposal.  This proposal is made in the absence of a higher quality source.

**Comment by efucile** [comment]
we could probably replace originating-center with originator. Just to clarify that it may be an entity that is not a center and that is not the previous existing table. I guess that we will need a controlled vocabulary for this and I would suggest it to go in codes.wmo.int

**Comment by petersilva** [comment]
@efucile are you pointing to adding to http://codes.wmo.int/common/centre ? or creating a new table?

**Comment by efucile** [comment]
we need new tables for WIS2

**Comment by tomkralidis** [comment]
cc @amilan17 

In TT-WISMD, we will start working on WCMP 2.0 codelists at https://github.com/wmo-im/wcmp2-codelists, and will kick off this activity at our [next meeting](https://github.com/wmo-im/wcmp/wiki/Meeting-2022-01-14#agenda).

**Comment by tomkralidis** [comment]
Updated tree:
```
|____data
| |____config
| |____outgoing
| |____public
| | |____YYYY-MM-DD
| | | |____source
| | | | |____tree-type
| | | | | |____country-code
| | | | | | |____originator
| | | | | | | |____data-category
| |____incoming
| | |____YYYY-MM-DD
| |____errors
| | |____YYYY-MM-DD
|____metadata
| |____discovery
| |____station
```

Closing this issue, given the implementation in wis2node proper.  Formal codelist creation will be put forth at TT-WISMD.

**Comment by tomkralidis** [comment]
Notes based on 2021-12-15 discussion:
- mirror config and incoming directory structures with public

Next steps:
- implement directory structure in incoming and config

@petersilva / @efucile thinking more:

```
| |____public
| | |____YYYY-MM-DD
| | | |____source
| | | | |____tree-type
| | | | | |____country-code
| | | | | | |____originator
| | | | | | | |____data-category
```

Example: `observations-surface-land.ca.cwao.landFixed`

Should we consider the data category higher up in the hierarchy, i.e.:

Ezxample

```
| |____public
| | |____YYYY-MM-DD
| | | |____source
| | | | |____tree-type
| | | | | |____data-category
| | | | | | |____country-code
| | | | | | | |____originator
```

Example: `observations-surface-land.landFixed.ca.cwao`

Thoughts?

**Comment by petersilva** [comment]
in hierarchies, normally, each level of the hierarchy has "control" of lower levels of the hierarchy.
This principle is expressed both in the OID mechanism ( discussed here: https://github.com/wmo-im/GTStoWIS2/issues/37 ) and was given by @remygiraud as a constraint on the hierarchy.

The country is supposed to be top... the national authority then can permit the next level of the tree (centre names within the country.)

So country-code.centre-id was a starting point for our committee work.

**Comment by tomkralidis** [comment]
After discussion with @efucile, should we add a level to the topic hierarchy based on the WMO Unified Data Policy, so:

- `core`
- `recommended`
- `other` ?

Example: `core.observations-surface-land.ca.cwao.landFixed`

Or is this a function of the discovery metadata evaluation (to assess whether to further bind to a resource)?

cc @petersilva @kaiwirt

**Comment by petersilva** [comment]
I don't know enough about the Unified Data Policy to understand the implications. I suspect that "core/recommended/other" is a distinction that is not material to most subscribers, who will not know what it means, or why it matters.  Questions:

* Are we saying that "core" roughly corresponds to traditional WMO 386/Volume C1 data?

* I guess a particular format of land observation is considered "core" by the WMO?

* Presumably, a BUFR ob would be in core, and a geojson for the same location in "other"?   

* If someone defines a new template, departing from the standard one, does that BuFR have to go under "other"?

* when the policy goes through revisions, and a new type gets accepted, do we have two locations and a transition period. (progression from "other" to "recommended" and later "core" in successive versions?)

**Comment by david-i-berry** [comment]
Core data is described here:

https://meetings.wmo.int/Cg-Ext-2021/_layouts/15/WopiFrame.aspx?sourcedoc=/Cg-Ext-2021/InformationDocuments/Cg-Ext(2021)-INF04-1-CATALOGUE-OF-CORE-DATA_en.docx&action=default

and resolution 1 / UDP here:

https://ane4bf-datap1.s3-eu-west-1.amazonaws.com/wmocms/s3fs-public/ckeditor/files/Cg-Ext2021-d04-1-WMO-UNIFIED-POLICY-FOR-THE-INTERNATIONAL-approved_en_0.pdf?4pv38FtU6R4fDNtwqOxjBCndLIfntWeR

The format or message type is not important by my reading and I would have thought (hoped) that the BUFR and geojson for the same observation would have the same classification, i.e. if the BUFR is classed as core data then the geojson should also be considered core. If this is not the case it then gets very messy.

I would have thought the easiest way to flag/control would be to have the classification within the topic hierarchy. If we do this do we also need to consider other data licensing models, for example provision under one of the creative commons licenses?

**Comment by petersilva** [comment]
I don´t know that format is irrelevant...  I gather (perhaps wrongly) that there are discussions between aviation and meteorological people, where the aviation community tends to want the Aviation XML to be limited access, perhaps only commercially available, and the Met community circulates BuFR obs publically with no restrictions for the same location.  Bufr being harder for non-met users to deal with, both communities are happy.   So I guess AvXML stuff would be non-core... 

From @david-i-berry´s links the core/etc... thing is more about distribution rights and requirements (must be available at no cost, vs. potentially restricted.) I don´t think most users care what the IP regime for data they are obtaining is (beyond whether they can access it or not.) 

Looking at the last link david provided... we a topic corresponding to "data policy license" with values like  "Attribution-NonCommercial-ShareAlike-CC-BY-NC-SA" (likely shortened to CC-BY-NC-SA ?) to distinguish between data set licensing, and then potentially identical trees under them.. with different content depend on how each product is licensed.

hmm...  Is that what people intend?

**Comment by tomkralidis** [comment]
I agree with @david-i-berry.  File format/representation should be independent from data management/identification.

**Comment by petersilva** [comment]
@david-i-berry ... that sounds like what I heard...possible optimization: source in the above tree is "WIS" ... from the discussions, @efucile was advocating getting rid of WIS, so we could just promote 'tree-type' up two levels, and have... say... WMO-Core just under the date, and WMO-Recommended, WMO-Other... etc... we save a level in the tree... and still get the concept in there.

**Comment by petersilva** [comment]
sorry, I just noticed tree-type is separate from "recommended" or "core" ... perhaps I misunderstood... I initially thought they were the same thing... I don't know what tree-type is.  I edited the previous comment... to omit discussion of tree-type.

**Comment by tomkralidis** [comment]
Implemented in initial iteration.  Will evolve in parallel with direction from WMO topic hierarchy efforts.
