### ISSUE TITLE
install fails on AlmaLinux

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#316]
Installing on AlmaLinux (`python3 wis2box-ctl.py start`) results in MinIO container being unhealthy.

cc @antje-s @kaiwirt

**Comment by tomkralidis** [comment]
Closing, given we specify [Ubuntu](https://docs.wis2box.wis.wmo.int/en/latest/user/getting-started.html) as the recommend OS.

**Comment by antje-s** [comment]
...the current version (1.0b3) can also be installed on AlmaLinux - we used [Quickstart with test data](https://docs.wis2box.wis.wmo.int/en/latest/reference/quickstart.html#) for our test installation 
@tkettenba thank you very much for the support and the hint

**Comment by tomkralidis** [comment]
Thanks @antje-s @tkettenba.  FYI a note has been added to the documentation in #462
