### ISSUE TITLE
security features are not enabled.

### ISSUE THREAD

**Issue by llazcano** [wmo-im/wis2box#317]
In Linux Mint xfce. I have this problem:

in this step: 
wis2box metadata discovery publish $WIS2BOX_DATADIR/metadata/discovery/mwi-surface-weather-observations.yml

Setting up logger with level: INFO
/usr/local/lib/python3.9/site-packages/elasticsearch-7.17.7-py3.9.egg/elasticsearch/connection/base.py:200: 
ElasticsearchWarning: **Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone.** See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html to enable security.

**Comment by tomkralidis** [comment]
@llazcano thanks for the report.  This as been fixed as part of #333 and will be part of a bugfix release shortly.
