### ISSUE TITLE
error in the creation of discovery metadata

### ISSUE THREAD

**Issue by maixino** [wmo-im/wis2box#318]
Dear All,
I would like to create discovery metadata from my xml files that I converted to yaml with the pygeometa project when I type the command wis2box metadata discovery publish $WIS2BOX_DATADIR/metadata/discovery/MD_2M_TempM.yml
I get this error message : Setting up logger with level: INFO
/usr/local/lib/python3.9/site-packages/elasticsearch-7.17.7-py3.9.egg/elasticsearch/connection/base.py:200: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchWarning)
Publishing discovery metadata from /data/wis2box/metadata/discovery/MD_2M_TempM.yml
[2022-11-06T05:59:55Z] {/usr/local/lib/python3.9/site-packages/pygeometa/core.py:308} INFO - MCF version: 1.0
Error: 'begin'
Can anyone help me?

## User story
As a (user type), I want to (task) so that (goal).

## Acceptance criteria

- [ ] acceptance criteria 1
- [ ] acceptance criteria 2
- [ ] acceptance criteria 3

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by tomkralidis** [comment]
@maixino thanks for the report.  Can you provide a metadata sample?

**Comment by maixino** [comment]
yes, I just sent you an example by email

**Comment by maixino** [comment]
Dear all

Here are some files attached.

Best regards

Le dim. 6 nov. 2022 à 16:20, Tom Kralidis ***@***.***> a
écrit :

**Comment by maixino** [comment]
[Climate and health Bulletin.zip](https://github.com/wmo-im/wis2box/files/9946170/Climate.and.health.Bulletin.zip)

**Comment by maixino** [comment]
Dear all,

Here are some files attached.

Best regards

[Monthly Climate Diagnostic bulletin for Africa.zip](https://github.com/wmo-im/wis2box/files/9946173/Monthly.Climate.Diagnostic.bulletin.for.Africa.zip)

**Comment by maixino** [comment]
Dear all,

I still have the same error.
I get this error message:

root@d8a42acd0d88:/home/wis2box# wis2box metadata discovery publish $WIS2BOX_DATADIR/metadata/discovery/MD_MLSPM.yml
Setting up logger with level: INFO
/usr/local/lib/python3.9/site-packages/elasticsearch-7.17.7-py3.9.egg/elasticsearch/connection/base.py:200: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchWarning)
Publishing discovery metadata from /data/wis2box/metadata/discovery/MD_MLSPM.yml
[2022-11-06T16:51:19Z] {/usr/local/lib/python3.9/site-packages/pygeometa/core.py:308} INFO - MCF version: 1.0
Error: 'begin'
root@d8a42acd0d88:/home/wis2box#

**Comment by maixino** [comment]
Dear All
I am still looking for solutions to put our metadata on WIS.
Can anyone help me?
Best Regards

**Comment by tomkralidis** [comment]
closing given discussion in https://github.com/geopython/pygeometa/issues/188
