### ISSUE TITLE
manage station metadata locally

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#324]
## User story
As a wis2box user, I want to be able to manage my own station metadata independent of the OSCAR/Surface M2M API, so that I can reduce design/real-time dependencies.

cc @david-i-berry @kurt-hectic 

## Acceptance criteria

- [ ] wis2box station metadata setup functions independent of the OSCAR/Surface M2M API
- [x] csv2bufr, csv2bufr-templates function independent of the OSCAR/Surface M2M API

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by david-i-berry** [comment]
The csv2bufr and csv2bufr-templates function independent of the OSCAR/Surface M2M API, as such I have marked that acceptance criteria as done. Within csv2bufr we provide for metadata to be supplied via JSON files but with no specification of the contents or encoding within the JSON. This can be WIGOS metadata or other metadata.

**Comment by kurt-hectic** [comment]
Hi @tomkralidis, 

the underlying issue I see here is the question where metadata should be managed, and also a policy issue of whether circulating data in WIS 2 has a requirement to have metadata (WIGOS, but also WIS really). 
IMHO we have already quite a lot of metadata, which is quite complicated as well. We need to make it easy for Members to maintain metadata. How to best maintain and publish all this metadata is very complicated. IMHO we should refrain from quick-fixes and look at the big picture. The community has invested a lot of resources into OSCAR/Surface as metadata catalogue. This is where metadata should be maintained and I am not totally convinced at this point that bringing another metadata management system into existence will help in the long run, for as much as I understand the desire to fix this in the box. 
Perhaps it would be better to allow data without metadata to circulate for the moment, pending a discussion and policy about relation of metadata and data in WIS2, or simply redirect a user to OSCAR/Surface? In OSCAR next gen there will be better APIs which could in principle allow to create a station from a wis2box in OSCAR.

@efucile I think we should bring the WIGOS colleagues into this discussion, too, but they are not on github, perhaps better by email?

**Comment by tomkralidis** [comment]
Hi @kurt-hectic good points here.  For the purpose of this issue we are not discussing (station) metadata management per se, but workarounds so as not to depends on the current OSCAR/Surface M2M API.  It is well known that OSCAR is the authoritative space for (station) metadata. We are not envisioning deep (station) metadata workflow in wis2box, which is representative in our current approach.  We need to revisit the approach in the context of external dependencies.

**Comment by tomkralidis** [comment]
Some notes from discussion with @david-i-berry and @webb-ben:

- wis2box requires station metadata (i.e. FM12 does not include geometry (x/y/z))
- wis2box needs periodic updates from OSCAR
  - would be valuable to have subscription service from OSCAR for clients in the future
- wis2box could download WMDR XML and utilize accordingly
- question then becomes how to access WMDR (M2M API endpoint or other)

**Comment by efucile** [comment]
@tomkralidis, @david-i-berry, @maaikelimper  and @webb-ben 
we should not make any dependency on OSCAR in the wis2box. This would result in operational problems if the system is unavailable or changes. There are frequent changes in the metadata model, and we cannot ask hundreds of nodes to update their software. We need to clarify that the metadata required for wis2box processing is the responsibility of the wis2box manager. He is responsible for updating the required metadata in the wis2box and OSCAR (in two different steps). 
wis2box should only check against the metadata provided by the wis2box manager, NOT querying OSCAR.
This must be documented, and the role of the wis2box manager has to be defined (@maaikelimper).

**Comment by tomkralidis** [comment]
Updates: initial steps to decouple from OSCAR
- csv2bufr: remove use of OSCAR JSON metadata
- wis2box: remove sync/caching of OSCAR
- data pipelines are data driven/derived
- station API publishing works off of default station list

**Comment by maaikelimper** [comment]
- don't add link to OSCAR in stations-collections
- add columns to station_list.csv: longitude, latitude, altitude, territory, wmo_region, facility_type
For future: consider requirements for moving stations
- remove 'wis2box station sync/cache' commands, use stations publish command
- add list-of-wigos-ids to discovery metadata, when users runs stations publish command

final result:
no requests made to OSCAR by wis2box
dots on wis2box-ui are associated to correct dataset, also when 0 data received

**Comment by david-i-berry** [comment]
As part of the discussion it would be helpful to clarify (both internally and to users / admins of the box) the purpose of the station API publishing and the links between the WIS2box and OSCAR/Surface. Particularly, we need to make clear that OSCAR/Surface remains the authoritative source / official repository for the WIGOS metadata.

From the WIS2box and data flow perspective I am not sure it matters whether this comes from OSCAR/Surface, a national database of stations or entered manually. However, it would be good to include the facility to convert from WMDR to the format required internally by the box. Members should be producing this already and so including this facility would remove another step required by them.

**Comment by tomkralidis** [comment]
- we can use pyoscar as an external workflow to download WMDRs and transform to CSV required by wis2box
  - possible output format of wis2box internal CSV
  - safeguard for collisions/overwrite
- needs docs on workflow

**Comment by tomkralidis** [comment]
WIP PR in #351
