### ISSUE TITLE
test/upgrade next ecCodes release

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#328]
The next ecCodes release (2.28, scheduled for Q1 2023) provides memory improvements for BUFR handling.  This issue is to ensure we test/upgrade/measure on release.

cc @david-i-berry @RoryPTB

**Comment by tomkralidis** [comment]
ecCodes [2.28.0](https://confluence.ecmwf.int/plugins/servlet/mobile?contentId=311148097#content/view/311148097) has been released, which provides memory improvements/updates.

- [ ] verify using csv2bufr directly
- [ ] verify within wis2box

We need to test and verify functionality (could also help #377).

**Comment by david-i-berry** [comment]
What do we need to verify in csv2bufr directly?

**Comment by tomkralidis** [comment]
1. we need to verify that there are no regressions
2. we can also test the removal the following in wis2box-management:

```yaml
    mem_limit: 1g
    memswap_limit: 1g
    restart: always
```

...in combination with testing with a burst of test data.

**Comment by tomkralidis** [comment]
Implemented via custom ecCodes base image.
