### ISSUE TITLE
Issue reported by Algeria: wis2box only read first message from ingested BUFR file

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#331]
"Recently, we noticed that not all of the station data was displayed on the WIS2BOX map. Upon further research, we learned that the system was only reading the first message from our BUFR files."

To reproduce issue, examble of bufr containing 5 messages in this zip:
[msg00001637.zip](https://github.com/wmo-im/wis2box/files/10030556/msg00001637.zip)

**Comment by david-i-berry** [comment]
Issue in bufr2geojson, fixed by PR16 (https://github.com/wmo-im/bufr2geojson/pull/16)

This is also likely present in the BUFR passthrough.
