### ISSUE TITLE
WIS2BOX Startup Issue

### ISSUE THREAD

**Issue by mgiannoni** [wmo-im/wis2box#355]
## WIS2BOX Startup Issue

$ python3 -V
Python 3.10.4

$ docker -v
Docker version 20.10.22, build 3a2c30b

$ docker-compose -v
Docker Compose version v2.14.1

$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        **modified:   Dockerfile**

no changes added to commit (use "git add" and/or "git commit -a")

$ git diff Dockerfile

> diff --git a/Dockerfile b/Dockerfile
> index ce64970..cfb4b18 100644
> --- a/Dockerfile
> +++ b/Dockerfile
> @@ -26,7 +26,7 @@ LABEL maintainer="tomkralidis@gmail.com"
>  ARG WIS2BOX_PIP3_EXTRA_PACKAGES
>  ENV TZ="Etc/UTC" \
>      DEBIAN_FRONTEND="noninteractive" \
> -    DEBIAN_PACKAGES="cron bash vim git libffi-dev libeccodes0 python3-eccodes python3-cryptography libssl-dev libudunits2-0 python3-paho-mqtt python3-dateparser python3-tz python3-setuptools"
> +    DEBIAN_PACKAGES="cron bash vim git **libgeos-dev** libffi-dev libeccodes0 python3-eccodes python3-cryptography libssl-dev libudunits2-0 python3-paho-mqtt python3-dateparser python3-tz python3-setuptools"

$ git log

> commit 4b6c7ddc9e7afe9f670f1e02e1fb09558654cea9 (HEAD -> main, origin/main, origin/HEAD)
> Author: Maaike <maaike.limper@gmail.com>
> Date:   Tue Dec 20 15:26:04 2022 +0100
> 
>     the default url should include the default port (#336)
> 
> commit b631afee5d366308bcf5bb56a4c0b98180c4dcb3
> Author: Maaike <maaike.limper@gmail.com>
> Date:   Tue Dec 20 15:24:18 2022 +0100
> 
>     documentation reorg (#349)
> 
>     * documentation reorg
> 
>     squash, documentation changes
> 
>     * doc review
> 
>     Co-authored-by: Tom Kralidis <tomkralidis@gmail.com>
> 
> commit 1055b2505e370a2061bd05e103c0252dcccc8c19
> Author: Maaike <maaike.limper@gmail.com>
> Date:   Fri Dec 9 16:39:22 2022 +0100
> 
>     remove wis2box-config bucket (#346)
> 
>     * remove wis2box-config bucket
> 
>     * Update configuration.rst
> 
>     Co-authored-by: Tom Kralidis <tomkralidis@gmail.com>
> 

$python3 wis2box-ctl.py start-dev

> wis2box exited with code 1
> wis2box                 | /etc/environment has been deprecated for locale information; use /etc/default/locale for LANG=C.UTF-8 instead ... (warning).
> wis2box                 | Starting periodic command scheduler: cron.
> wis2box                 | /etc/environment has been deprecated for locale information; use /etc/default/locale for LANG=C.UTF-8 instead ... (warning).
> wis2box                 | cron is running.
> wis2box                 **| Missing data mappings: [Errno 2] No such file or directory: '/data/wis2box/data-mappings.yml'**
> wis2box                 | Traceback (most recent call last):
> wis2box                 |   File "/usr/local/lib/python3.9/site-packages/wis2box-0.6.dev1-py3.9.egg/wis2box/data_mappings.py", line 33, in <module>
> wis2box                 |     with open(os.environ.get('WIS2BOX_DATADIR_DATA_MAPPINGS')) as fh:
> wis2box                 | FileNotFoundError: [Errno 2] No such file or directory: '/data/wis2box/data-mappings.yml'
> wis2box                 |
> wis2box                 | During handling of the above exception, another exception occurred:
> wis2box                 |
> wis2box                 | Traceback (most recent call last):
> wis2box                 |   File "/usr/local/bin/wis2box", line 33, in <module>
> wis2box                 |     sys.exit(load_entry_point('wis2box==0.6.dev1', 'console_scripts', 'wis2box')())
> wis2box                 |   File "/usr/local/bin/wis2box", line 25, in importlib_load_entry_point
> wis2box                 |     return next(matches).load()
> wis2box                 |   File "/usr/local/lib/python3.9/importlib/metadata.py", line 86, in load
> wis2box                 |     module = import_module(match.group('module'))
> wis2box                 |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
> wis2box                 |     return _bootstrap._gcd_import(name[level:], package, level)
> wis2box                 |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> wis2box                 |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> wis2box                 |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> wis2box                 |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> wis2box                 |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
> wis2box                 |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> wis2box                 |   File "/usr/local/lib/python3.9/site-packages/wis2box-0.6.dev1-py3.9.egg/wis2box/__init__.py", line 26, in <module>
> wis2box                 |     from wis2box.api import api
> wis2box                 |   File "/usr/local/lib/python3.9/site-packages/wis2box-0.6.dev1-py3.9.egg/wis2box/api/__init__.py", line 25, in <module>
> wis2box                 |     from wis2box.api.backend import load_backend
> wis2box                 |   File "/usr/local/lib/python3.9/site-packages/wis2box-0.6.dev1-py3.9.egg/wis2box/api/backend/__init__.py", line 25, in <module>
> wis2box                 |     from wis2box.env import API_BACKEND_TYPE, API_BACKEND_URL
> wis2box                 |   File "/usr/local/lib/python3.9/site-packages/wis2box-0.6.dev1-py3.9.egg/wis2box/env.py", line 29, in <module>
> wis2box                 |     from wis2box.plugin import load_plugin
> wis2box                 |   File "/usr/local/lib/python3.9/site-packages/wis2box-0.6.dev1-py3.9.egg/wis2box/plugin.py", line 27, in <module>
> wis2box                 |     from wis2box.data_mappings import DATADIR_DATA_MAPPINGS
> wis2box                 |   File "/usr/local/lib/python3.9/site-packages/wis2box-0.6.dev1-py3.9.egg/wis2box/data_mappings.py", line 40, in <module>
> wis2box                 |     raise EnvironmentError(msg)
> wis2box                 **| OSError: Missing data mappings: [Errno 2] No such file or directory: '/data/wis2box/data-mappings.yml'**
> wis2box exited with code 1
>

**Comment by maaikelimper** [comment]
Hi,
This looks like a configuration issue.
Could you review if you setup your configuration as outlined in the documentation:
https://docs.wis2box.wis.wmo.int/en/latest/user/setup.html

If that does not address your issue, please let check the settings of the environment variables WIS2BOX_HOST_DATADIR and WIS2BOX_DATADIR_DATA_MAPPINGS in your dev.env and ensure a data-mappings.yml-file is defined in the directory defined by WIS2BOX_HOST_DATADIR

**Comment by tomkralidis** [comment]
Hi @mgiannoni : can we close this specific issue?  As discussed today, I think you were able to stand up wis2box (latest) and are investigating persmission issues on your OS?
