### ISSUE TITLE
docs build fails

### ISSUE THREAD

**Issue by webb-ben** [wmo-im/wis2box#366]
With the updates to creating wis2box-management (https://github.com/wmo-im/wis2box/pull/362), the root directory no longer has `requirements-dev.txt`, breaking the [RTD build](https://readthedocs.org/projects/wis2box/builds/19243008/).

```
git clone --no-single-branch --depth 50 https://github.com/wmo-im/wis2box.git .
git checkout --force origin/main
git clean -d -f -f
python3.7 -mvirtualenv 
python -m pip install --upgrade --no-cache-dir pip setuptools<58.3.0
python -m pip install --upgrade --no-cache-dir pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.3
python -m pip install --exists-action=w --no-cache-dir -r requirements-dev.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements-dev.txt'
```

**Comment by tomkralidis** [comment]
Fixed. Updated reference to requirements file to `wis2box-management/requirements-dev.txt` in RTD setup.  Build passes again. https://readthedocs.org/projects/wis2box/builds/19247830

Thanks!
