### ISSUE TITLE
add station metadata editor UI

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#376]
## User story
As an operator, I want to have access to a user interface to manage station metadata, so that I can manage my stations using a web-based editor/wizard.

## Acceptance criteria

- [ ] wis2box-ui contains a view with a station metadata editor
- [ ] user can publish station metadata to the wis2box API / catalogue

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

cc @david-i-berry

**Comment by tomkralidis** [comment]
Example: https://github.com/wmo-im/wis2box/blob/main/tests/data/metadata/station/station_list.csv

**Comment by tomkralidis** [comment]
- should have something to demo in the next two weeks

**Comment by jmaxmarno** [comment]
Station Metadata Manager (Table)
![image](https://user-images.githubusercontent.com/9143887/224826634-f203d7b7-f73d-4e6a-901d-dd260fa0992b.png)

Individual Station Metadata Editor
![image](https://user-images.githubusercontent.com/9143887/224828612-99341c01-1fd8-42fd-8375-a8161c54208d.png)

Station Status (options)
![image](https://user-images.githubusercontent.com/9143887/224828717-cd09304d-5125-467e-a21a-43291af5b283.png)

Basic form validation (prevents submission)
![image](https://user-images.githubusercontent.com/9143887/224828806-a5c217d8-3acc-4dae-b05d-0ad0d1190ddd.png)

**Comment by tomkralidis** [comment]
- pull codelists from authoritative
- add build time step
  - pull from WMDS / codes.wmo.int
  - store as JavaScript lookups

**Comment by tomkralidis** [comment]
![image](https://user-images.githubusercontent.com/910430/229844146-d64c2915-49b0-470e-82f9-2d2a7fe96e32.png)

**Comment by tomkralidis** [comment]
First pass implemented in wis2box-ui-admin in experimental mode.
