### ISSUE TITLE
mosquitto can bring down wis2box due to max_queued_messages 0

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#377]
wis2box-australia kept crashing which I traced due to out of control memory usage in mosquitto.

I did a test on wis2box-australia last night setting "max_queued_messages 100000" in mosquitto.conf which appears to have helped to cap the memory-growth:
![image](https://user-images.githubusercontent.com/19169339/214517854-217af9d8-fe64-4f27-abca-2687e558d53e.png)

I'd need to investigate what is causing the message-queue build-up in wis2box-australia first place. 

I still recommend we set back "max_queued_messages" in mosquitto back to a non-0 value in the next release (for sprint-009)

**Comment by golfvert** [comment]
What are the MQTT parameters used by the client when it connects to mosquitto? 
If you have both the retain flag and QOS of 1 or 2, messages are kept in the queue up to the possible number of messages or the size of the queue.

**Comment by efucile** [comment]
please try to use the new version of eccodes https://confluence.ecmwf.int/plugins/servlet/mobile?contentId=311148097#content/view/311148097

**Comment by tomkralidis** [comment]
#381 has been opened to specificaly address the ecCodes update.
