### ISSUE TITLE
Incorrect example wis2box/examples/config/surface-weather-observations.yml

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#384]
Using the example wis2box/examples/config/surface-weather-observations.yml

Will result in the error:
`Error: sequence item 0: expected str instance, dict found`

when using this .yml in the commands 'wis2box metadata discovery publish' or 'wis2box data add-collection'

**Comment by maaikelimper** [comment]
It would be good if we could retro-actively fix the archive for wis2box-1.0b1-release to include the fixed examples once this issue is addressed.

**Comment by tomkralidis** [comment]
Fixed via #385.  `wis2box-setup-1.0b1.zip` archive updated on the [1.0b1 release page](https://github.com/wmo-im/wis2box/releases/tag/1.0b1).
