### ISSUE TITLE
wis2box pubsub issues

### ISSUE THREAD

**Issue by alimand** [wmo-im/wis2box#391]
## User story
As a wis2box message subscriber(I build wis2box A for subscribing), I want to subscribe message from another wis2box (I build wius2box B for publishing) , so that I can real test message pubsub functionality by using wis2box.

## Acceptance criteria

- [ ] acceptance criteria 1
       Step 1: in wis2box B: 
       run:
       **wis2box metadata discovery publish $WIS2BOX_DATADIR/metadata/discovery/mwi-surface-weather-observations.yml**
       (successful)
      Step 2: in wis2box A: 
       Refer to the documentation https://docs.wis2box.wis.wmo.int/en/1.0b1/user/downloading-data.html
       in “Downloading data from WIS2” chapter I run:
          a.**pywis-pubsub schema sync**
          b.**pywis-pubsub subscribe --config local.yml**
      However, I have issue like this: Message is not a valid notification {...} is not valid under any of the given schemas.
![1](https://user-images.githubusercontent.com/48341438/217126028-e8059e26-f6fc-474f-829e-5b76da86adcb.png)

- [ ] acceptance criteria 2
       Step 1: in wis2box B: 
       run:
       **wis2box data ingest --topic-hierarchy mwi.mwi_met_centre.data.core.weather.surface-based-observations.synop --path $WIS2BOX_DATADIR/observations/malawi**
      Step 2: in wis2box A: 
       Refer to the documentation https://docs.wis2box.wis.wmo.int/en/1.0b1/user/downloading-data.html
       in “Downloading data from WIS2” chapter I run:
          a.**pywis-pubsub schema sync**
          b.**pywis-pubsub subscribe --config local.yml**
      However, I have issue like this: ValidationError: "version" is a required property.
![2](https://user-images.githubusercontent.com/48341438/217126007-f3e0399c-bb7e-47d8-b927-a7dc11bd0679.png)

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by tomkralidis** [comment]
The broker to which wis2box is subscribing to is not providing valid notification messages.  Is broker you are subscribing to a wis2box based broker?  If yes, what version of wis2box is installed? wis2box should be emitting valid messages.

Else if the broker is not based on wis2box, suggest this issue is filed in https://github.com/wmo-im/wis2pilot/issues for discussion.

**Comment by alimand** [comment]
Hi Tom,

1.Yes,I think so.
(I'm following the official documentation:https://docs.wis2box.wis.wmo.int/en/latest/user/downloading-data.html,
![79368c216dc1c573ac02a4b07408153](https://user-images.githubusercontent.com/48341438/217138542-105efc4f-02d1-48fb-adc9-2ac65f7f9455.png)
following theses steps:
    a. modify local.yml like this:
![4714463eb66ec57660cfd2fe98c55b6](https://user-images.githubusercontent.com/48341438/217138592-9356d9d7-e81f-4139-9efe-6e669a410e0e.png)
    b.run docker-compose -f docker-compose.subscribe-download.yml up -d --build). 
    c.follow acceptance criteria steps before, then have this issue.

2.The version of wis2box I installed is **1.0.beta1**.
![2fab586ac2b2ab6116fc4e81cab7fdf](https://user-images.githubusercontent.com/48341438/217138721-eb2772fe-ccaf-46cd-bb58-e168b4d707f0.png)

Looking forward to your kind reply! Really thanks.

**Comment by tomkralidis** [comment]
Thanks for the feedback @alimand.  Can you copy/paste the notification messages that are being produced by wis2box?

**Comment by alimand** [comment]
Sure.@tomkralidis 
The complete message wis2box produces is as follows:

**{
 "id": "WIGOS_0-454-2-AWSBALAKA_20211118T095500",
 "type": "Feature",
 "version": "v04",
 "geometry": {
  "type": "Point",
  "coordinates": [15.0, 35.0, 618.0]
 },
 "properties": {
  "data_id": "origin/a/wis2/mwi/mwi_met_centre/data/core/weather/surface-based-observations/synop/WIGOS_0-454-2-AWSBALAKA_20211118T095500.bufr4",
  "pubtime": "2023-02-08T09:53:34Z",
  "integrity": {
   "method": "sha512",
   "value": "f247f9cccedbd60dd03d2aec028c20626dfdafd436883e528ea8188e07c1fba9b558c5ff6323702b792bd2b79161f014379f739643d022865a75e69dd5812de3"
  },
  "wigos_station_identifier": "0-454-2-AWSBALAKA"
 },
 "links": [{
  "rel": "canonical",
  "type": "application/x-bufr",
  "href": "http://10.0.49.23:8999/data/2021-11-18/wis/mwi/mwi_met_centre/data/core/weather/surface-based-observations/synop/WIGOS_0-454-2-AWSBALAKA_20211118T095500.bufr4",
  "length": 247
 }]
}**

Manys thanks!

**Comment by alimand** [comment]
Sure.
The complete message wis2box produces is as follows:

{
"id": "WIGOS_0-454-2-AWSBALAKA_20211118T095500",
"type": "Feature",
"version": "v04",
"geometry": {
"type": "Point",
"coordinates": [15.0, 35.0, 618.0]
},
"properties": {
"data_id": "origin/a/wis2/mwi/mwi_met_centre/data/core/weather/surface-based-observations/synop/WIGOS_0-454-2-AWSBALAKA_20211118T095500.bufr4",
"pubtime": "2023-02-08T09:53:34Z",
"integrity": {
"method": "sha512",
"value": "f247f9cccedbd60dd03d2aec028c20626dfdafd436883e528ea8188e07c1fba9b558c5ff6323702b792bd2b79161f014379f739643d022865a75e69dd5812de3"
},
"wigos_station_identifier": "0-454-2-AWSBALAKA"
},
"links": [{
"rel": "canonical",
"type": "application/x-bufr",
"href": "http://10.0.49.23:8999/data/2021-11-18/wis/mwi/mwi_met_centre/data/core/weather/surface-based-observations/synop/WIGOS_0-454-2-AWSBALAKA_20211118T095500.bufr4",
"length": 247
}]
}

Many thanks!

**Comment by alimand** [comment]
Hi,Tom. Thanks for your reply!
Sure. 
The complete notification message wis2box produces is as follows:

{
 "id": "WIGOS_0-454-2-AWSBALAKA_20211118T095500",
 "type": "Feature",
 "version": "v04",
 "geometry": {
  "type": "Point",
  "coordinates": [15.0, 35.0, 618.0]
 },
 "properties": {
  "data_id": "origin/a/wis2/mwi/mwi_met_centre/data/core/weather/surface-based-observations/synop/WIGOS_0-454-2-AWSBALAKA_20211118T095500.bufr4",
  "pubtime": "2023-02-08T09:53:34Z",
  "integrity": {
   "method": "sha512",
   "value": "f247f9cccedbd60dd03d2aec028c20626dfdafd436883e528ea8188e07c1fba9b558c5ff6323702b792bd2b79161f014379f739643d022865a75e69dd5812de3"
  },
  "wigos_station_identifier": "0-454-2-AWSBALAKA"
 },
 "links": [{
  "rel": "canonical",
  "type": "application/x-bufr",
  "href": "http://10.0.49.23:8999/data/2021-11-18/wis/mwi/mwi_met_centre/data/core/weather/surface-based-observations/synop/WIGOS_0-454-2-AWSBALAKA_20211118T095500.bufr4",
  "length": 247
 }]
}

**Comment by tomkralidis** [comment]
Hi @alimand this has been fixed in #394 and will be part of the 1.0.b2 release.
