### ISSUE TITLE
can not define custom csv2bufr json mappings-template 

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#405]
In the latest version of wis2box I note that the template defined by the user is prepended with MAPPINGS:
https://github.com/wmo-im/wis2box/blob/main/wis2box-management/wis2box/data/csv2bufr.py#L49

        mapping_bufr4 = Path(MAPPINGS) / self.template

This makes it hard/impossible to provide a custom ccsv2bufr json mappings-template 

Could we please make it so a user can simply define a path such as /data/wis2box to easily share the custom mappings-file :

plugins:
            csv:
                - plugin: wis2box.data.csv2bufr.ObservationDataCSV2BUFR
                  template: /data/wis2box/mappings.json
                  notify: true
                  file-pattern: '^WIGOS_(\d-\d+-\d+-\w+)_.*\.csv$'

**Comment by david-i-berry** [comment]
The following commit broke the use of user defined templates:

https://github.com/wmo-im/wis2box/commit/0e1345885bd113953bce0180fb5a3caab54ad036

**Comment by david-i-berry** [comment]
Solution (untested)

Revert 

https://github.com/wmo-im/wis2box/blob/c9662e305876f3e3e4daadb529975ea7cee079f3/wis2box-management/wis2box/data/csv2bufr.py#L49 

to 

`mapping_bufr4 = DATADIR_CONFIG / "csv2bufr" / self.template`

and reinsert:

`from wis2box.env import DATADIR_CONFIG`

**Comment by tomkralidis** [comment]
Option:

```python
        if self.template.startswith('/'):
            mapping_bufr4 = self.template            
        else:
            mapping_bufr4 = Path(MAPPINGS) / self.template
```

**Comment by tomkralidis** [comment]
PR in #406
