### ISSUE TITLE
need to repeat 'wis2box metadata station publish-collection' to see data after first observation received

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#410]
A user currently needs to rerun 'wis2box metadata station publish-collection' to see data in the wis2box-ui after first observation is received for that data. Is there anyway to automate this process? 
There is also currently nothing that alerts the users that this step needs to be taken due to missing links?

**Comment by maaikelimper** [comment]
@tomkralidis 
I noted that if I run data ingest before having manually executed 'wis2box metadata station publish-collection' the data notifications go out while the API is not updated. Maybe it would be better if there was a process internally to ensure the file metadata/station/station_list.csv and the api-endpoint oapi/collections/stations are in sync. Such a process could at least be run at container-startup and perhaps also run periodically   ?

**Comment by tomkralidis** [comment]
FYI #413 implements station publishing on startup as well as every 10 minutes.  The sync is needed so as to link incoming observations to stations, which is then utilized by the UI.  Note that this will change once a station metadata UI is implemented as part of a future sprint/release.
