### ISSUE TITLE
add SHIP support/pipeline

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#411]
## User story
As a wis2box user, I would like support for SHIP processing, so that I can publish via wis2box.

## Acceptance criteria

- [ ] pipeline integration

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by david-i-berry** [comment]
@tomkralidis can we close, this is now included in https://github.com/wmo-im/wis2box/issues/629
