### ISSUE TITLE
clarify valid/invalid BUFR file

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#426]
(moving from offline disussion with @david-i-berry)

Currently, the wis2box BUFR plugin checks / injects / discards as follows:
- geometry: if none found, injected from station list
- WSI: if none found, injected from station list
- temporal: if none found, discarded

Does the absence of temporal information constitute an invalid BUFR message?

**Comment by efucile** [comment]
The message is not invalid BUFR, but it is unusable if the observation time is not present.
