### ISSUE TITLE
wis2Box ENVIROMENT CREATION

### ISSUE THREAD

**Issue by Omary1982** [wmo-im/wis2box#429]
## User story
As a (user type), I want to (task) so that (goal).
Hi, I'm Omary Saidi from TMA of Tanzania, I'm Colleague of Rose Senyagwa. We are practicing the implementation of wis2box node on our side. We have reached at Environment creation point refers to attached picture.

I want to know if we can assign ftp:// to the host instead of the http:// and the box can work correctly? Another issue is, username, and password are these created as new object, or are the credentials of the current host?
## Acceptance criteria

- [x] acceptance criteria 1
![WIS2BOXTMA](https://user-images.githubusercontent.com/51920290/228769597-b8b74564-0a36-4083-a98a-47be1b898ece.PNG)

- [ ] acceptance criteria 2
- [ ] acceptance criteria 3

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by tomkralidis** [comment]
Hi: thanks for the report.  FTP is not a supported protocol of wis2box.  The credentials are of the hosts that are created as part of wis2box, not the credentials of your host system.  Note that wis2box builds a number of containers/services WITHIN your host.
