### ISSUE TITLE
Problems with publishing metadata using wis2box

### ISSUE THREAD

**Issue by alimand** [wmo-im/wis2box#454]
## User story
As a WIS2 node by using wis2box, I want to publish our country metadata message notifications via wis2box so that GDCs and GBs can subscribe our metadata message notification and/or download.

## Acceptance criteria

- [ ] acceptance criteria 1
According to wis2box documentation：
[](https://docs.wis2box.wis.wmo.int/en/latest/reference/running/api-publishing.html)
We use this command to publish our test metadata: 
**wis2box metadata discovery publish /path/to/discovery-metadata.yml**
By using MQTT Explorer, we successfully subscribe our metadata message notification **but it is different from the observation data message notification, may I ask whether it is correct and whether it meets the requirements?**

we found that by using MQTT Explorer, subscribing to France GB, some country who publish metadata message notification seems to conform to WIS2 node requirements (**like Germany[deu] metadata message notification**).
However, the metadata message notification we published through **wis2box(1.0b3)** seems too long and looks incorrect.
Could you pls give us some help and advice? Thank you very much.
## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by tomkralidis** [comment]
Confirm, it looks like the WCMP2 record itself is being published.  This will be updated as part of the next wis2box release (so 1.0b4).

**Comment by alimand** [comment]
@tomkralidis Thanks for your kind reply. May I ask when 1.0b4 will be release? So that we can quickly follow the new one.Thanks.

**Comment by tomkralidis** [comment]
@alimand we should have a 1.0b4 release in the coming days.
