### ISSUE TITLE
admin tools: setup wis2box configuration without editing files

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2box#465]
## User story
As a wis2box administrator without IT skills, I want to be able to configure the wis2box without editing configuration files so that my instance is ready to run without the need to ask for external support.

## Acceptance criteria

- [ ] all the basic configurations are done via tools
- [ ] documentation is available to use the tools

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by maaikelimper** [comment]
Files currently used by wis2box for configuration:
- dev.env
- data-mappings.yml
- station_list.csv
- mappings.json (for csv2bufr)
- discovery-metadata yml ?

We need to break-up this work to address the various files and configuration-types used. 
Some work was already done on discovery-metadata and station-list-editor how can we combine this work ?

I propose @efucile plans a meeting with Tom/Maaike and we agree on how we want to plan this work so we have something by October (Indonesia).

**Comment by maaikelimper** [comment]
We will have station-metadata editor to edit the station_list.csv

Other files can be generated by the using wis2box-create-config.py

**Comment by tomkralidis** [comment]
Completed first pass.
