### ISSUE TITLE
sample CSV template that works with csv2bufr without requiring custom column-mapping-template

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#466]
Feedback from WIS2 workshop in CMO: Users would like a sample CSV template in which they can enter data that works with csv2bufr without having to provide custom column-mapping-template.

Dave, could you help provide such a sample CSV template that contains all possible columns, along with the mapping.json? 

I can then assist in providing the documentation and ensuring the default mapping.json is included in the wis2box-release.

**Comment by maaikelimper** [comment]
this sample CSV template could be used as the standard for industry

**Comment by maaikelimper** [comment]
@david-i-berry to provide reference in manual to be used as starting point for CSV template for synoptic observations

**Comment by david-i-berry** [comment]
The relevant regulations are described in the Manual on Codes, see the INFCOM-2 amendments.  The sequence starts on page 43, only those with an entry in the GBON regulation must be included.

[INFCOM-2-d06-3(3)-UPDATE-OF-THE-MANUAL-ON-CODES-approved_en.pdf](https://github.com/wmo-im/wis2box/files/11832621/INFCOM-2-d06-3.3.-UPDATE-OF-THE-MANUAL-ON-CODES-approved_en.pdf).

**Comment by maaikelimper** [comment]
@efucile we noted that the number of variables with an entry in the GBON regulation are relatively limited. 

For example "Cloud amount and type" would not be required by GBON but it is required by World Weather Watch Global Observing System, see https://library.wmo.int/doc_num.php?explnum_id=11157#page=136 

Can you advise what would be an appropriate reference for the variables listed in the sample CSV template ?

**Comment by efucile** [comment]
It is in the same document referenced by @david-i-berry. In BUFR sequence 3 07 096 we have all the GBON variables + all the other variables. GBON variables are mandatory for GBON the rest is optional. However most of the optional parameters are not reported by AWS and are meant to be reported by a human observer. We don't need to include them in a csv because in that case we are going to use a manual entry with two possible options
1. entry box for SYNOP
2. entry form with all the observed parameters for SYNOP. In this case the CSV will be behind the scene

**Comment by efucile** [comment]
This document specifies what is required from an AWS 
[TT-GBON-tender-AWS-amended-22062023.docx](https://github.com/wmo-im/wis2box/files/11833197/TT-GBON-tender-AWS-amended-22062023.docx)

**Comment by maaikelimper** [comment]
This GitHub-issue was intended to cover the request from the CMO workshop to have a sample CSV template that works with csv2bufr without requiring a custom-mapping-template.

Does that mean this GitHub-issues would requires 2 sample CSV-template :
One CSV-template for data collected by Automated Weather Stations, which will be the standard proposed for industry
One CSV-template for observed parameters for SYNOP, to be transformed into entry form once we have the interface for this

?

**Comment by maaikelimper** [comment]
adding @scottylad501 (Dwayne) as he raised this as follow-up item from the workshop .

**Comment by efucile** [comment]
synop2bufr is made by a SYNOP decoder + csv2bufr. We already have a CSV template for TAC SYNOP. The interface for the observer is a long-term solution, and I suggest not giving a CSV to be filled in by the observer. We need a proper interface to help with quality control. The short-term solution is to keep producing manually TAC SYNOP, and we can provide a web UI to enter the text, do QC and convert to BUFR before sending.
The CSV for AWS can be easily provided. It is the only CSV example we need to provide.

**Comment by tomkralidis** [comment]
@david-i-berry to add to csv2bufr-template repository.

**Comment by tomkralidis** [comment]
Changes folded into csv2bufr proper, available in the v0.7.0 release, to be updated in wis2box-management and wis2box-api.

**Comment by tomkralidis** [comment]
in csv2bufr 0.7.3:
- fixed CSV format
- mapping
- we should move templates back out to csv2bufr-templates to prevent ongoing release requirements
- needs docs in wis2box

**Comment by tomkralidis** [comment]
> we should move templates back out to csv2bufr-templates to prevent ongoing release requirements

Closing this issue, with follow up in #546
