### ISSUE TITLE
include oscar2wis2box.py in wis2box-management container ?

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#469]
Shall we include oscar2wis2box.py in the wis2box-management container as a temporary solution to help people setup a station-list ?

**Comment by tomkralidis** [comment]
Suggest we park this until we have a better idea of station metadata management and the OpenCDMS station management integration.

**Comment by maaikelimper** [comment]
Closing this issue, we now have multiple solutions that emulate oscar2wis2box in wis2box-1.0b5:
- In wis2box-managment: wis2box metadata station get
- In wis2box-api: oapi/processes/oscar2feature
