### ISSUE TITLE
wis2box does not work with docker/compose v2

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#471]
wis2box-ctl.py uses the commands `docker-compose` rather than `docker compose` inside the wis2box-ctl.py script

Excerpt from the internet:

_The docker compose (with a space) is a newer project to migrate compose to Go with the rest of the docker project. This is the v2 branch of the [docker/compose](https://github.com/docker/compose/tree/v2) repo. It's been first introduced to Docker Desktop users, so docker users on Linux didn't see the command. In addition to migrating to Go, it uses the compose-spec, and part of the rewrite may result in behavior differences.

The original python project, called docker-compose, aka v1 of docker/compose repo, has now been deprecated and development has moved over to v2. To install the v2 docker compose as a CLI plugin on Linux, supported distribution can now install the docker-compose-plugin package. E.g. on debian, I run apt-get install docker-compose-plugin._

wis2box should be made compatible with docker/compose v2

**Comment by tomkralidis** [comment]
Moving to `docker compose` makes sense for the long term.  This will require an update to `wis2box-ctl.py` as well as docs.

**Comment by isedwards** [comment]
I substituted using `docker compose` by creating the name that wis2box required as an executable in `/usr/bin`. I've not noticed any problems.
```
/usr/bin$ cat docker-compose 
#!/bin/bash
docker compose "$@"
```

Could `wis2box-ctl.py` try `docker compose` and then fall back to `docker-compose`?
