### ISSUE TITLE
Entry form for SYNOP

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2box#479]
## User story
As an observer, I want to be able to access a Web application providing a text box so that I can write or copy a SYNOP and send it in BUFR format through WIS2. I need to have an error message if the SYNOP is malformed. The error message has to tell me where the SYNOP is wrong. I need to check that the data in the BUFR file are correct. Therefore I need to see the values encoded in the BUFR.
As an observer, I don't know the required metadata. A metadata administrator shall be able to edit the metadata used by the SYNOP to BUFR converter.
The Web application has to provide user authentication and can be used for other purposes if different roles are available. For example, an administrator could access a UI for the box's configuration, and an operator could access monitoring tools. A WIS2 box could serve different countries; in this case, the observer from a country should be able to send SYNOP messages only for his country.

## Acceptance criteria

- [ ] observer from country X can access a Web application to send SYNOP for country X
- [ ] SYNOP converter sends back an error if the message is malformed
- [ ] SYNOP converter sends notification and share message as required by WIS2

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by tomkralidis** [comment]
Initial implementation in 1.0b5.
