### ISSUE TITLE
add view to show messages published in wis2box-webapp

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#480]
In a recent test where Namibia uploaded temp-data, I noted that the WIS2-message was successfully published (I received the message by subscribing to the MQTT-broker before uploading the data) but I noted there was no way to see the published data in the wis2box-ui.

I think wis2box is missing an interface where a user can easily view the messages that are published on each topic. 

In theory the data is already available at the api-endpoint oapi/collections/messages ?

**Comment by tomkralidis** [comment]
Is the scope for locally generated notifications or those from WIS2 Global Broker for all messages?

Locally, yes, the notifications are always available via wis2box-api in `/collections/messages/items` in support of the WIS2 Replay API concept.

**Comment by maaikelimper** [comment]
Yes I meant for locally generated notifications. 
As we are discussing moving to a new and improved wis2box-ui framework, I would  like to highlight the requirement to have a UI-component that takes data from `/collections/messages/items` and displays the number of WIS2-notifications broken down by stations and topic ...
The current wis2box-ui does not meet this requirement.

**Comment by tomkralidis** [comment]
Who is the user for this requirement?  Can you provide a user story?

**Comment by maaikelimper** [comment]
User story:
As a user I want to see the notifications that have been published for each dataset configured in the wis2box. I would like to be able to download the bufr from the notifications and inspect the content of the bufr through the User Interface.

**Comment by maaikelimper** [comment]
this is being developed as the "monitoring"-page in the wis2box-webapp

![image](https://github.com/wmo-im/wis2box/assets/19169339/56685199-1774-4980-8059-59841bbdec2a)

**Comment by tomkralidis** [comment]
- code needs some refactoring
- wis2box-webapp needs integration into wis2box docker setup
- needs addition of filter by station and temporal
- consider adding a map

**Comment by tomkralidis** [comment]
- Initial capability in wis2box-webapp
- next sprint will need docs updates
