### ISSUE TITLE
add UI page for SYNOP conversion to BUFR

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#489]
Implement UI page to allow an authenticated user to paste SYNOP data for conversion into BUFR.  The UI should send a request to wis2box-api and render the results, and have an additional 'publish to WIS2' button to automatically enable publishing workflow from the UI.

**Comment by tomkralidis** [comment]
UI needs update for notification (or not) workflow.  Requires API review (@tomkralidis).

**Comment by maaikelimper** [comment]
awaiting a new version of synop2bufr to be deployed on the test-server

**Comment by tomkralidis** [comment]
- Initial implementation is part of 1.0b5
- issues in synop2bufr
  - station name needs to be encoded
  - cloud height checks (edge case)
 - does not break data exchange
