### ISSUE TITLE
add wis2box-api process to convert synop2bufr and optionally publish

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#490]
Add an OGC API - Processes process to wis2box-api pygeoapi setup to utilize synop2bufr to transform SYNOP to BUFR and publish to broker/WIS2.  The process should allow for an input to publish to WIS2.

**Comment by tomkralidis** [comment]
PR in https://github.com/wmo-im/wis2box-api/pull/28

**Comment by maaikelimper** [comment]
Preliminary testing lead us to found some additional issues in synop2bufr. We will need to a new version of synop2bufr to be used in the new wis2box-api

**Comment by tomkralidis** [comment]
Initial implementation in wis2box-api 1.0b5 release tag.

Future sprint will need some refactoring between wis2box-management and wis2box-api.
