### ISSUE TITLE
add option in UI to download and inspect bufr-files published by the wis2box

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#492]
To allow the users easy access to the bufr-files produced by wis2box, we should add a function to download bufr from the UI rather than going via MinIO. To allow the user to view the content in the BUFR, we can add an 'inspect'-option using bufr2geojson as demonstrated in this screenshot:
![image](https://github.com/wmo-im/wis2box/assets/19169339/9f6be3ff-bf66-408c-ac4e-89c5e91da68d)

**Comment by tomkralidis** [comment]
Duplicate of #480

**Comment by tomkralidis** [comment]
Sorry closed the wrong issue.  Reopened.

**Comment by maaikelimper** [comment]
![image](https://github.com/wmo-im/wis2box/assets/19169339/5534daee-132f-4d2d-b1aa-473f3285c0b2)

**Comment by maaikelimper** [comment]
implemented in wis2box-1.0b5 closing
