### ISSUE TITLE
help on data ingest

### ISSUE THREAD

**Issue by davidgondwe** [wmo-im/wis2box#503]
Hello, I have a few questions for someone to help me today...I have successfully installed Wis2box in Ubuntu 22.04 and did a few configurations and is running okay but I have a few difficulties before I can go further.
1, I created a bucket in MinIO and then created a path /test/data...Then I uploaded TAC files with the hope I would see them in the grafana but that was not the case because it shows no station has sent data
2. my question is it necessary for the files to be in BUFR format?
3. Is there a package/script that I can install to help me convert TAC messages into BUFR? i have tried to follow the training material on this with no success.

**Comment by maaikelimper** [comment]
Hi David,

The wis2box can help you convert files to BUFR using the plugins defined in data-mappings.yml

The documentation here explains how to setup your wis2box and to defined the require configuration files:
https://docs.wis2box.wis.wmo.int/en/latest/user/setup.html

Please note that ingested data is to be placed in the "wis2box-incoming" bucket to trigger data ingestion. Data ingestion using MinIO is documented here:
https://docs.wis2box.wis.wmo.int/en/latest/user/data-ingest.html

If you can provide me with an example TAC file you would like to ingest I can help provide you with a valid data-mappings.yml example and provide you additional instructions to help you ingest your data.

**Comment by davidgondwe** [comment]
Thanks so much, Maaikelimper for your support...please find the attached file below you more help on the data-mappings.yml configuration. The file was in a notepad pad I had to copy it to a Word document to be compatible here.
[SMTN01 HTDA 010600 RRA.docx](https://github.com/wmo-im/wis2box/files/12499051/SMTN01.HTDA.010600.RRA.docx)

**Comment by davidgondwe** [comment]
Sorry ...on the issue of the bucket...What I did is create a bucket named wis2box-incoming and then create a path named /test/data where I dump my files; is this correct?

**Comment by davidgondwe** [comment]
Please check my station_list.csv file if it is correct also...i hope to see station DAR ES SALAAM INT in my wis2box web but that is not the case ...what might be the reason?
[station_list.csv](https://github.com/wmo-im/wis2box/files/12513216/station_list.csv)

**Comment by chenxiaoxia2019** [comment]
@davidgondwe  Hi, David, thanks for reaching out to us. Could you please write an email to wis2-support@wmo.int so that we are able to track the progress on this issue?

**Comment by davidgondwe** [comment]
Thank you Chenxiaoxia2019 for your advice ... I will do what have advised.
