### ISSUE TITLE
issue associating a station with a dataset

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#505]
The wis2box automatically associates a station to a dataset after data for that station is seen in the corresponding folder/topic.

This causes the following issues:
- when a station is accidentally ingested into the wrong folder/topic, the station is no longer displayed in the other folder/topic after ingestion move to another dataset
- when a single wigos-station-identifier represents data for 2 datasets (for example surface/temp stations in India) the data is only displayed in the wis2box-ui for the first dataset

**Comment by maaikelimper** [comment]
I noted that the issue in the code is here:
https://github.com/wmo-im/wis2box/blob/main/wis2box-management/wis2box/metadata/station.py#L197-L198

As it associates the station to the first topic in the topics-list.

@tomkralidis How about we re-write the code such that `upsert_collection_item('stations', feature)` inserts one feature per station-and-topic in the "stations"-collection ?

**Comment by maaikelimper** [comment]
Tom to investigate alternative solution using topics as an array in the feature. Needs to be tested.

**Comment by maaikelimper** [comment]
We are moving to topics as an array in the feature, wis2box-api:1.0b5 will have an update in station_info process to filter on topic

**Comment by tomkralidis** [comment]
needs refactoring on topic strings (infrastructure elements `origin/a/wis2` handling).
