### ISSUE TITLE
station_list.csv misses barometer_height

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#511]
As per discussion with David Berry, we need to add barometer_height to the station_list.csv

**Comment by maaikelimper** [comment]
Dave to provided proper definition for barometer_height to be added to the documentation

**Comment by maaikelimper** [comment]
To be addressed by https://github.com/wmo-im/wis2box/pull/513

**Comment by tomkralidis** [comment]
If barometer height is missing, we should keep as missing.

- known issue/needs fix: https://github.com/wmo-im/wis2box/blob/main/wis2box-management/wis2box/metadata/station.py#L189
