### ISSUE TITLE
Separators and format of field "wmo:topicHierarchy" in index `discovery-metadata`

### ISSUE THREAD

**Issue by Jolik** [wmo-im/wis2box#522]
In the index `discovery-metadata` in the "wmo:topicHierarchy" field, a topic is now written with a slash delimiter (see example "wmo:topicHierarchy": "mwi/mwi_met_centre/data/core/weather/surface-based-observations/synop").

This is right?

But it is not MQTT topic (channel)!

Moreover, in the original example of metadata in the MCF format, a similar `topic_hierarchy` field is presented with a dot separator (see example `topic_hierarchy: mwi.mwi_met_centre.data.core.weather.surface-based-observations.synop`).

It seems to me that the "wmo:topicHierarchy" field in index `discovery-metadata` should have a full copy of the `topic_hierarchy` field from the metadata with a dot delimiter. 

No?

**Comment by maaikelimper** [comment]
@tomkralidis I thought this was fixed, can we close this ?

**Comment by tomkralidis** [comment]
Note that `wmo:topicHierarchy` is no longer a part of WCMP2 discovery metadata, but is used internally in wis2box.  Closing.
