### ISSUE TITLE
Originating centre and sub centre incorrect in BUFR generated by wis2box

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/wis2box#536]
Whilst the originating centre and sub centre in BUFR data generated by the wis2box (via synop2bufr and csv2bufr) can be set by configuring the csv2bufr mapping files this has not been done for the vast majority of wis2box's currently installed.

With the new configuration workflow this could be done via an environment variable and then using this environment variable via the API and event driven workflows.

**Comment by tomkralidis** [comment]
We should ensure the value is null/missing rather than incorrect.

**Comment by tomkralidis** [comment]
- default is null
  - template changes in synop2bufr/csv2bufr

**Comment by tomkralidis** [comment]
2024-01-17
- updated as part of csv2bufr-template refactor
- needs update in synop2bufr
- needs testing/release management

**Comment by david-i-berry** [comment]
wis2box docs need updating to instruct user how to update originating centre (some initial instructions provided as part of the Jakarta training material).

**Comment by tomkralidis** [comment]
2024-01-30
- @RoryPTB / @david-i-berry to update synop2bufr
- add docs in this issue for docs PR

**Comment by RoryPTB** [comment]
**Update:** 
When the BUFR header centre and subcentre are not set in the mapping file, the default is not none but rather 98 and 0 respectively. So, it appears that ECMWF are setting the defaults to their own if it is missing. Hence the use of environment variables `BUFR_ORIGINATING_CENTRE` and `BUFR_ORIGINATING_SUBCENTRE` should be mandatory.

**Comment by tomkralidis** [comment]
Thanks @RoryPTB.  Can we (in the BUFR handler) force unset these values in any way? Or is the result the same?

**Comment by david-i-berry** [comment]
See also https://github.com/wmo-im/wis2box/issues/546

**Comment by tomkralidis** [comment]
2024-03-05:
- fixed in API, will be fixed once API updates are merged/integrated to stack

**Comment by tomkralidis** [comment]
Closing.  Will monitor as wis2box BUFR production circulates across WIS2.
