### ISSUE TITLE
update BUFR plugin to use ecCodes directly

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#551]
The [BUFR plugin](https://github.com/wmo-im/wis2box/blob/main/wis2box-management/wis2box/data/bufr4.py#L28) currently uses bufr2geojson to parse a given BUFR and interact with it.  It will be valuable to, instead, use ecCodes (Python) directly for parsing and inspection as part of BUFR publishing.

**Comment by david-i-berry** [comment]
See https://github.com/wmo-im/wis2box-api/pull/51

**Comment by david-i-berry** [comment]
@tomkralidis this can be closed, resolved by PR #51 linked above.
