### ISSUE TITLE
add checkbox to publish BUFR data as an update

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#552]
If a user wants to upload/publish data via wis2box-webapp, include a checkbox indicating if the data is a data update.

- set data update accordingly in BUFR payload
- set notification message as an update (https://wmo-im.github.io/wis2-notification-message/standard/wis2-notification-message-DRAFT.html#_links) (Requirement 11F).

**Comment by maaikelimper** [comment]
will be done within the publish workflow similar to resolution for other issue
