### ISSUE TITLE
Implement discovery metadata editor in wis2box-webapp

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#566]
#154 implemented an experimental mode discovery metadata UI (in https://github.com/wmo-im/wis2box-ui-admin).  We need to update the UI to the framework put forth in https://github.com/wmo-im/wis2box-webapp.

**Comment by tomkralidis** [comment]
- @RoryPTB to put forth first pass, to meet thereafter (week of 15 January 2024)

**Comment by tomkralidis** [comment]
- need to discuss standalone application requirements and reusability
- to put up live demo for next week

**Comment by tomkralidis** [comment]
2024-01-30
- to be discussed during feedback session on 2024-02-02, to feed updates

**Comment by tomkralidis** [comment]
2024-02-13:
- remove `wis2box.retention` from MCF files (cleanup uses retention default env var), we can revisit later as required for dataset specific retention/cleanup

**Comment by tomkralidis** [comment]
@tomkralidis TODO

**Comment by RoryPTB** [comment]
@RoryPTB TODO: Add duplicate fields to the output JSON, such as topic hierarchy and ID, to ensure the metadata is correctly displayed in the wis2box.
