### ISSUE TITLE
align functionality between wis2box-api (transform) and wis2box-management (publish)

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#572]
The latest version of wis2box is using 'wis2box-1.0b6'-branch of the wis2box-api to allow us to implement the synop-form in the wis2box-webapp.

We need to review the workflow in wis2box to allow us to move back to using the wis2box-api:main branch. The current situation should not be maintained as we end up having to align code in multiple places.

**Comment by maaikelimper** [comment]
We discussed how to align the function between wis2box-api and wis2box-management container. 

Maaike proposes that we make wis2box-managment responsible for publishing, and wis2box-api provides the currently implemented data-conversions via processes

wis2box-api:
- receives data and converts data via processes
- store data in wis2box-public based on notify=true/false boolean

wis2box-management:
- any data landing in wis2box-public is published: "passthrough"-data-plugin run on any file in this bucket
- data lands in wis2box-incoming: existing data-mapping determine what plugin in wis2box.data to be used 
- different wis2box.data plugins post the received data to different wis2box-api process

**Comment by maaikelimper** [comment]
After further investigation I noted that the transform has to been to run as asynchroneous proccesses both for performance reasons and to keep the memory-space separated. I've tested locally that I can successfully run wis2box-transformations as async jobs:
![image](https://github.com/wmo-im/wis2box/assets/19169339/1b06031b-b818-49f1-ad95-c5bb6f080062)

Using async jobs will also require the following additional work:
- wis2box-webapp to be updated to poll job-status and return output from /oapi/jobs/<job-id>/results?f-=json when the job is finished
- an additional process to cleanup old jobs (cronjobs in wis2box-management?)

**Comment by maaikelimper** [comment]
Note: need to prepare a benchmark to compare impact of performance of moving data-transformation to API

**Comment by maaikelimper** [comment]
we discussed a sensible default for cleaning up jobs in a cronjob: DELETE request on all successfully completed jobs older than one hour

**Comment by maaikelimper** [comment]
the message sent by the wis2box-api requesting data publication is defined by https://github.com/wmo-im/wis2box/wiki/PubSubInternalMessageBusSpec

**Comment by tomkralidis** [comment]
@tomkralidis to review wis2box-api and wis2box PRs on 19 January

**Comment by tomkralidis** [comment]
Yes, release tags will be put forth when we release (they are unpinned during a development cycle).

**Comment by tomkralidis** [comment]
2023-02-13: @tomkralidis to review https://github.com/wmo-im/wis2box-api/pull/45 (job cleanup/management)

**Comment by tomkralidis** [comment]
2024-03-05
- BUFR tools (synop2bufr) need updating and integration
