### ISSUE TITLE
Add user-login screen and role-based access control to wis2box-webapp

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#573]
In order to implement the wis2box-webapp in wis2box-1.0b5 we used a temporary solution using wis2box-auth tokens.

What we actually wanted to have was a web-application that was secured behind a common auth solution in the stack so that the user accessing the wis2box-webapp would go via a login-screen.

This issue can not be resolved until we sort out the new auth solution in the stack. We can use this issue to track the progress on addressing this.

**Comment by tomkralidis** [comment]
- depends on #488 implementation
- need to discuss whether/how much customization is required

**Comment by maaikelimper** [comment]
we never added KeyCloak to the stack, instead we have a login-screen using basic auth on wis2box-webapp. 
Improvement to the authentication setup in wis2box are to be tracked in new GitHub-issues once we agree on away forward. 
Closing
