### ISSUE TITLE
Replace DATADIR_DATA_MAPPINGS with data_mappings-dict loaded by new subscribe-class

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#591]
Rewrite wis2box.pubsub.subscribe, wis2box.handler and wis2box.plugin to pass 'data_mappings'-dict to replace DATADIR_DATA_MAPPINGS

This will allow data-mappings to be loaded from a different endpoint in the future by updating the function in the subscribe-class and allow us to move away from file-based data-mappings.yml

**Comment by tomkralidis** [comment]
- to be covered during this week
