### ISSUE TITLE
Improve documentation for "station metadata" and clarify relationship between wis2box and OSCAR

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#605]
I regularly receive questions from my WMO colleagues on how data from OSCAR relates to the wis2box station metadata which can not be answered by the documentation.

We need to update the documentation here:

 https://docs.wis2box.wis.wmo.int/en/latest/reference/running/station-metadata.html

And clearly describe how station metadata is used in the wis2box:
- document relationship between plugins and station metadata
- document the use of the wis2box-webapp station editor
- document the relationship with the topic-hierarchy in the station metadata

**Comment by tomkralidis** [comment]
- how wis2box interacts with OSCAR/Surface
- need overall picture of workflows
