### ISSUE TITLE
Docs logo does not work

### ISSUE THREAD

**Issue by webb-ben** [wmo-im/wis2box#606]
The logo.png provided in the 1.0b6 release of wis2box includes a local reference to the WMO logo, which does not render in the HTML of the docs.
<img width="1359" alt="image" src="https://github.com/wmo-im/wis2box/assets/40066515/b5cfe56a-02c4-45bd-bc59-eaaaf98269d7">

**Comment by maaikelimper** [comment]
Yes I noticed, this is due to the new WMO-website... 
To resolve this, without wasting too much time, I simply updated the wmo-sphinx-theme to remove the link:

![image](https://github.com/wmo-im/wis2box/assets/19169339/d6e7dce5-c53d-40d9-b337-bd364d10fdbc)


better no logo than a broken link...
