### ISSUE TITLE
review request to integrate universal pipeline

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#607]
From Peiwen Jin from CMA.
_"We developed a small grib pipeline plugin(simple publish NWP grib2 data with no error) and we contribute them in our publc repository (including readme documentation, code and test data sample) 
See the link: https://github.com/alimand/CMA-grib-pipeline-plugin.git 
May I know if this work could be contribute to wis2box? 
"_

In order to commit this work into work @alimand will need to checkout the wis2box-repository, create a new branch with the additional plugin. 

@tomkralidis can you comment on the best way to integrate this into the latest version of wis2box ?

**Comment by tomkralidis** [comment]
Thanks @alimand.  You can fork wis2box, work in your own branch, and submit a pull request.  Given there is already an implementation and test data, we will work together on documentation at which point it should be then available for the 1.0b7 release.

**Comment by tomkralidis** [comment]
- to be further discussed by wis2box dev team during sprint week/next week
