### ISSUE TITLE
error displaying data other than surface-based-observations/synop

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#609]
As reported by Iran: 

_upper air data was ingested and published successfully.
But, there is an error in the UI in displaying the stations even after I republished station metadata after data ingestion. I attached the screen shot of the error._

![UI_temp_err](https://github.com/wmo-im/wis2box/assets/19169339/0766355c-976f-4ff4-b00e-ca1c0dcd7e41)

Let's try to address this in the upcoming sprint in the work integrating the web interfaces

**Comment by tomkralidis** [comment]
- we can add an `api=true|false` to the plugin definition, for example
- or we can adjust/update UI to handle different data types
- needs discussion (next week)

**Comment by maaikelimper** [comment]
To be addressed in this issue :
https://github.com/wmo-im/wis2box/issues/571

**Comment by maaikelimper** [comment]
closing. to be addressed in #571
