### ISSUE TITLE
UI-issue wis2box-brazil

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#610]
The UI for Brazil is displaying the following issue:

![image](https://github.com/wmo-im/wis2box/assets/19169339/72c0cd7d-45b5-48dc-9a68-398f5db0f31f)

I noted that the following call is made by the map which returns 403 forbidden:
http://wis2bra.inmet.gov.br/oapi/collections/urn:x-wmo:md:br-inmet:surface-based-observations.synop/items?f=json&datetime=2024-01-09T12:00:00Z%2F..&wigos_station_identifier=0-76-0-2915601000000514&limit=321

While this API-call works successfully:
http://wis2bra.inmet.gov.br/oapi/collections/urn:x-wmo:md:br-inmet:surface-based-observations.synop/items?f=json&datetime=2024-01-09T12:00:00Z&wigos_station_identifier=0-76-0-2915601000000514&limit=321

I see two issues: 
Why does the API return 403 forbidden when datetime is formatted differently ?
Why does the UI give datetime=2024-01-09T12:00:00Z%2F.. as input ?

**Comment by tomkralidis** [comment]
I think the map is asking for a time range.  It appears as if the `/..` in the `datetime` parameter is causing issues.  More examples:

- works: http://wis2bra.inmet.gov.br/oapi/collections/urn:x-wmo:md:br-inmet:surface-based-observations.synop/items?f=json&datetime=2024-01-09T12:00:00Z/2024-01-09T13:00:00Z&wigos_station_identifier=0-76-0-2915601000000514&limit=321
- 403: http://wis2bra.inmet.gov.br/oapi/collections/urn:x-wmo:md:br-inmet:surface-based-observations.synop/items?f=json&datetime=../2024-01-09T13:00:00Z&wigos_station_identifier=0-76-0-2915601000000514&limit=321

**Comment by maaikelimper** [comment]
The logs provided by Jose show there the API is crashing:
![GRAFANA (002)](https://github.com/wmo-im/wis2box/assets/19169339/13b8b3ff-32aa-42ef-ad2e-724ccfa8fd97)

**Comment by webb-ben** [comment]
The error is caught at line 329 of elaticsearch_.py - something goes wrong parsing the OAF datetime query. Possibly an issue from updating the backend to elasticsearch 8?

**Comment by tomkralidis** [comment]
The issue is not specific to the API.  Anytime `..` is passed in the URL, a 403 is the result. Example: http://wis2bra.inmet.gov.br/?foo=..&

Infact, the issue is not specific to wis2box proper (thanks @webb-ben).  Example: https://portal.inmet.gov.br/?foo=..&

It looks like there is a ProxyPass or Apache front end that is causing this behaviour.

**Comment by maaikelimper** [comment]
I've reported the issue to Jose, as there is nothing to fix for this issue in our release, I will remove the sprint-014 milestone
