### ISSUE TITLE
WMO Region 7 Antarctica

### ISSUE THREAD

**Issue by kornada** [wmo-im/wis2box#627]
WMO Region 7 Antarctica cannot be added to station descriptions

**Comment by david-i-berry** [comment]
The next version of the wis2box will use the code list directly from https://codes.wmo.int/wmdr/_WMORegion, this should resolve the issue.

**Comment by david-i-berry** [comment]
@kornada the latest version of the station editing form now uses the code list from codes.wmo.int, including Antarctica. Please see the screen shot below and the current main branch.

![image](https://github.com/wmo-im/wis2box/assets/29403616/17710435-45ef-4fea-bbe6-c7e314f4de13)

For you second comment, on the traditional station identifier, please note that the purpose of this field in the station metadata form is to allow linking between the identifiers in BUFR (typically the block and station number, ship call sign or buoy number) and the WIGOS station identifier. The form is not intended to replace or replicate the contents of OSCAR/Surface.

**Comment by david-i-berry** [comment]
Closing, @kornada please open another issue if required.
