### ISSUE TITLE
bufr2bufr pipeline support for non synop/temp

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#629]
Test/update existing bufr2bufr pipeline to be compatible with following non synop/temp datatypes:

- surface-based-observations/buoy
- surface-based-observations/ship
- surface-based-observations/snow (?)
- surface-based-observations/wind_profiler

This will allow us to support these additional data-types as per sprint-014 roadmap

**Comment by david-i-berry** [comment]
Checklist:

### surface-based-observations/ship

- [ ] Discovery metadata
- [ ] Sample data files
- [ ] Station list updated
- [ ] Tests updated

### surface-based-observations/buoy

- [ ] Discovery metadata
- [ ] Sample data files
- [ ] Station list updated
- [ ] Tests updated 

### surface-based-observations/wind_profiler

- [ ] Discovery metadata
- [ ] Sample data files
- [ ] Station list updated
- [ ] Tests updated

**Comment by david-i-berry** [comment]
PR opened: https://github.com/wmo-im/wis2box/pull/635

**Comment by tomkralidis** [comment]
- snow data should be on GTS or from ECMWF (consult w/ Rodica)
- Synoptic snow data can provide an example
- open dedicated issue for BUFR snow data inclusion
