### ISSUE TITLE
wis2box-webapp import station from OSCAR crash due to new codelists

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#639]
The new codelists in wis2box-webapp do no work with the current implementation of ImportOSCAR.vue

![image](https://github.com/wmo-im/wis2box/assets/19169339/f6f99d9f-a7d6-4396-bd57-f6e56a133b6d)

https://github.com/wmo-im/wis2box-webapp/blob/main/src/components/ImportOSCAR.vue#L358-L359

**Comment by david-i-berry** [comment]
@maaikelimper I think this has been fixed by #33, #34 and #35.
