### ISSUE TITLE
add security property to link in data-notification for access-controlled data

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#643]
When we add an access-token to secure the data using 'wis2box auth add-token' , the wis2box-management container needs to add a security-property to the link of the data:

![image](https://github.com/wmo-im/wis2box/assets/19169339/aa2cd994-c60d-4992-8ee8-9294760731c0)

**Comment by tomkralidis** [comment]
2024-07-24:
- add access control information to WCMP2 `wis2box` section
- data notifications can check for access control from dataset metadata
  - apply `links.security` object
  - suppress `properties.content.value`
  - wis2box-auth updates metadata

@tomkralidis to take a look.

**Comment by tomkralidis** [comment]
2024-08-19:
- wis2box-auth should update discovery metadata security object
- CLI needs to update WCMP2 record `wis2box`

**Comment by tomkralidis** [comment]
@tomkralidis to double check whether WCMP2 output needs `security` objects on protected links.
