### ISSUE TITLE
codes.wmo.int returns empty CSV lists for FacilityType and InstrumentOperatingStatus

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#658]
wis2box uses codes.wmo.int to store/use some WMDR codelists to validate local station metadata values.

We are downloading these codelists as part of the wis2box-management container build (https://github.com/wmo-im/wis2box/blob/main/wis2box-management/Dockerfile#L56-L59).

FacilityType and InstrumentOperatingStatus CSVs return 0 bytes.  To reproduce:

```bash
curl -s "https://codes.wmo.int/wmdr/FacilityType?_format=csv&status=valid" > /tmp/FacilityType.csv
curl -s "https://codes.wmo.int/wmdr/InstrumentOperatingStatus?_format=csv&status=valid" > /tmp/InstrumentOperatingStatus.csv
```

Not sure if this is related to the recent codes.wmo.int system upgrades.

**Comment by maaikelimper** [comment]
Hi Tom,
I noted that the following query does work:
`https://codes.wmo.int/wmdr/FacilityType?_format=csv&_view=with_metadata&status=valid`

But in that case the 'skos:notation' would be in row[6] instead of row[4] when parsing the codelists
https://github.com/wmo-im/wis2box/blob/main/wis2box-management/wis2box/metadata/station.py#L81

I will check with Timo tomorrow what's going wrong in the WDMR-repository.

**Comment by amilan17** [comment]
I think it's a known bug. Did this work before the upgrade?

**Comment by tomkralidis** [comment]
> I think it's a known bug. Did this work before the upgrade?

Yes, this was a working part of the build.

**Comment by tomkralidis** [comment]
This has since been fixed by codes.wmo.int.

**Comment by maaikelimper** [comment]
@tomkralidis could we reapply the fix I made previously for this issue ? The dependency on codes.wmo.int interferes with the automated testing

**Comment by tomkralidis** [comment]
@maaikelimper I'd like to check with @amilan17 first to better assess the issue on codes.wmo.int.

**Comment by tomkralidis** [comment]
FYI note sent to UK MetOffice.

**Comment by tomkralidis** [comment]
Given we haven't heard back yet from UK MetOffice, I've issued #707 as a temporary workaround.
