### ISSUE TITLE
wis2box 1.0b7: Error submitting data: API not found

### ISSUE THREAD

**Issue by chenxiaoxia2019** [wmo-im/wis2box#679]
José reported that Graphana shows the messages are being received but not published.
![image](https://github.com/wmo-im/wis2box/assets/58480226/732d08b8-0c25-41e0-a4e9-4afcf67ece4e)

**Comment by maaikelimper** [comment]
I have updated the wis2box-api image now to resolve this issue.

To fix your installation please perform the following actions:
-	Stop the wis2box: python3 wis2box-ctl.py stop
-	Delete the api-config volume: docker volume rm wis2box_project_api-config
-	Update the wis2box-images: python3 wis2box-ctl.py update
-	Start the wis2box: python3 wis2box-ctl.py start

This should clear the “API not found”-error and allow you to submit the dataset.
