### ISSUE TITLE
wis2box does not restart properly when VM or docker-system restarts

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#683]
Currently a restart results in only a subset of the services restarting and the proxy ends up bouncing as it does not find the required endpoints.
The docker-compose.yml files for wis2box should be updated to allow all wis2box-services to restart properly when the docker-host-system restarts.

**Comment by tomkralidis** [comment]
2024-07-24:
- @maaikelimper to check w/ @alimand on status/updates

**Comment by tomkralidis** [comment]
2024-08-19:
- fixed in main branch
