### ISSUE TITLE
FM 12 bulletin guidance for web-app users

### ISSUE THREAD

**Issue by alimand** [wmo-im/wis2box#696]
## User story
As a user who is not familiar with the FM 12 bulletin,  he/she wants to see some guidances or tips on what information should he/she put in Raw FM 12 bulletin box so that he can publish related observation data in correct way based on his/her requirements on WIS2.
![image](https://github.com/wmo-im/wis2box/assets/48341438/7c81f6cd-06c8-467d-836d-366f7b6610ff)

**Comment by david-i-berry** [comment]
Update docs to include information from: https://training.wis2box.wis.wmo.int/practical-sessions/converting-synop-data-to-bufr/

**Comment by tomkralidis** [comment]
2024-07-24:
- data should already be in FM-12 if using the FM-12 form
- add info link to wis2box-webapp on FM-12 proper? @david-i-berry to provide link for both webapp and docs
