### ISSUE TITLE
Guidance for wis2box-webapp user on submitting correct CSV format file

### ISSUE THREAD

**Issue by alimand** [wmo-im/wis2box#697]
## User story
As a user, I want to see the guidance about the CSV Form schema when I use wis2box-webapp tool to submit personal CSV Data so that I can avoid some warnings /errors when wis2box-webapp do the preview/validate process.
![image](https://github.com/wmo-im/wis2box/assets/48341438/5e46eee5-01b6-4119-a138-35f41476bee0)

**Comment by david-i-berry** [comment]
The following page:

https://docs.wis2box.wis.wmo.int/en/1.0b7/user/data-ingest.html#the-aws-template-in-csv2bufr-plugin 

needs to be updated to include:

https://training.wis2box.wis.wmo.int/practical-sessions/converting-csv-data-to-bufr/

**Comment by tomkralidis** [comment]
2024-07-24:
- provide content in docs (training materials can link to docs)
- add to csv2bufr-templates repository
- @david-i-berry to address

**Comment by tomkralidis** [comment]
Fixed in #746
