### ISSUE TITLE
wis2box-ctl.py csv-files 

### ISSUE THREAD

**Issue by gespau** [wmo-im/wis2box#698]
I was reading through the [documentation](https://docs.wis2box.wis.wmo.int/en/1.0b7/reference/administration.html) and then some code to familiarize myself with wis2box. I think the following function `walk_path()` in the code snippet finds python-scripts instead of csv-files as indicated in the comments. Is this intended? 

https://github.com/wmo-im/wis2box/blob/1ab6e170a1403f69e85c6746c3ef44e367e7e665/wis2box-ctl.py#L107-L121

**Comment by maaikelimper** [comment]
by the way @wis2gsa  may I ask who you are , and what is your interest in wis2box , so that I may better assist you ?

**Comment by wis2gsa** [comment]
I just started at https://geosphere.at and we will implement wis2.0 with the wis2box in the close future

**Comment by maaikelimper** [comment]
Great thanks for the information! 
If your organization will be responsible for publishing data from Austria's National Meteorological Services, becoming familiar wis2box would be useful. You can also contact WMO WIS2 team at wis2-support@wmo.int for queries not directly related to wis2box, such at the registration of the WIS2-node for Austria ;)
