### ISSUE TITLE
add data pipeline for CAP alerts

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#704]
Notes:

### Entry point
- given workflow will / can arrive from the CAP editor, add wis2box-api processing plugin to upload to s3/MinIO

### Plugin
- subclass universal data plugin
- add XML validation check (will require caching of CAP XML Schema)
- add signature check (XML SIG)

**Comment by maaikelimper** [comment]
@tomkralidis @RoryPTB  can you please provide the following to help get started with this:
- source where CAP XML Schema will be cached from
- sample input-file of CAP XML and topic to be used in the automated testing
- example output after the signature check is added

**Comment by tomkralidis** [comment]
2024-07-24:
- baseline pipeline working
- some signatures are self signed, how to address this issue?

ACTION:
- we need business rules / input on accepting CAP messages with self-signed signatures
- we need to validate the requirement for XML signature handling

cc @efucile

**Comment by david-i-berry** [comment]
We also have the WMO register of alerting authorities, see https://alertingauthority.wmo.int/

**Comment by tomkralidis** [comment]
2024-08-14:

- data pipeline developed
- composer work includes MQTT publication settings
- needs management functionality in wis2box proper to enable credentials
- define `WIS2BOX_BROKER_USERNAME_CAPEDITOR`, `WIS2BOX_BROKER_PASSWORD_CAPEDITOR` in wis2box environment
- wis2box broker entrypoint creates CAP username/password if env vars exist
- loop for any `WIS2BOX_BROKER_USERNAME_*` and set if exists
- need to address `metadata_id` issues
  - create dataset metadata record
  - use metadata id in CAP Composer

**Comment by tomkralidis** [comment]
2024-08-19:
- @tomkralidis to review PR
- broker entrypoint loops/checks for `WIS2BOX_BROKER_USERNAME_*`; if found, then update acl and mosquitto conf
