### ISSUE TITLE
new API-process to display dataset_info to users

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#719]
While supporting the wis2box-users I have noted that many users get confused by the information displayed in the wis2box-ui.

The wis2box-ui relies on bufr2geojson and an association between stations and topics, driven by the 'station_info'-api-process.

If any of these processes fail or are misconfigured, the user will be see errors, or the data displayed will not correspond to the data that is published on WIS2.

In order to improve the information displayed to users I propose to introduce a new API-process "dataset_info" that could be used by the wis2box-ui (and the webapp) to provide the users with additional information

**Comment by maaikelimper** [comment]
as per the discussion with @efucile and @tomkralidis the wis2box-ui should not show internal issues. I will limit the scope of the dataset_info-process to display information about WIS2-notifications published, allowing the users to distinguish between issues with bufr2geojson/station_info and data-transmission.

**Comment by maaikelimper** [comment]
I've created the new process 'dataset-info' and made it available for testing on the test-server.

![image](https://github.com/user-attachments/assets/daac464f-e20b-4211-a20d-4c10eefbc50a)

**Comment by tomkralidis** [comment]
2024-08-14:
- make response more neutral/generic (@tomkralidis to provide feedback)
