### ISSUE TITLE
update station metadata command to associate all stations in csv to topic

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#720]
Dear Tom,

We received the following user-request:
```
There is an issue that would be great if it could be addressed in the next release. 
There are about 400 local stations (converted from climatological to synop) in Iran which have to be associated to the recommended topic. It is very difficult to associate all of them using station metadata editor one by one or using the command (wis2box metadata station add-topic –wsi …) .
 
Would you please add an option to associate a list of stations in one command to a topic? At the moment it is possible to add the whole stations or  a territory but not  a list of stations (as far as I know).
 
Best Regards
```

This issue has been raised by other users before and is a result of the "station metadata publish-collection" relying on a predefined file-path and the topic-association being done separately.

@tomkralidis can we make an update such that a user can run the command:
`wis2box station metadata publish-collection -p /data/wis2box/station_list_mynewtopic.csv -th origin/a/wis2/mynewtopic`

**Comment by tomkralidis** [comment]
Implemented in #723 (thanks @maaikelimper for the additional fixes).
