### ISSUE TITLE
receive wis2box alerts by e-mail

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#734]
Peiwen recently tested how to send alerts from Grafana by e-mail. This requires changes in the Grafana configuration that are not easily scripted. I propose for the wis2box documentation be updated to explain how users can configure Grafana to receive alerts by e-mail.

**Comment by alimand** [comment]
See in https://github.com/wmo-im/wis2box/tree/issue-734
Add related information in Monitoring:
<img width="480" alt="d4f9dd39-b85b-4ddd-ad26-cb7952ecf483" src="https://github.com/user-attachments/assets/8f4c4770-463f-4af6-b6e0-583fd5d4353c">
![43e8a016-e8bc-4c37-867c-c4fa0a06497a](https://github.com/user-attachments/assets/33c73b4f-52f6-48ee-9486-6c0a5d1a5f58)
![ffad2bcf-ad5b-4f99-bf31-de11fe655390](https://github.com/user-attachments/assets/0e0a450d-badf-482a-b25a-e95a98fea96d)
![70be7cb2-d805-424f-951d-9688119ac446](https://github.com/user-attachments/assets/9d6f9a75-5a97-4e3e-a2e6-b9c4cad892dd)
![849494ee-14af-4d7b-9887-f503e21a6df2](https://github.com/user-attachments/assets/0fedd15c-c154-453d-929e-2d4ab24cfa92)
![404e34d4-febb-4316-87b2-5dfffc7b2c41](https://github.com/user-attachments/assets/5190473c-9091-4544-94cb-c80c9547b3b9)
