### ISSUE TITLE
wis2box-webapp to use dataset-ids in dropdowns

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#735]
to align to dataset-centric approach the wis2box-webapp to use dataset-ids in dropdown, currently webapp does not work correctly in monitoring page

**Comment by tomkralidis** [comment]
Needs API updates.

**Comment by tomkralidis** [comment]
2024-08-20:
- implemented, needs testing

**Comment by tomkralidis** [comment]
Addressed in https://github.com/wmo-im/wis2box-webapp/pull/57, needs review/merge/test/validate.

**Comment by tomkralidis** [comment]
Merged/validated.
