### ISSUE TITLE
wis2downloader to use from image built by wis2downloader repository

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#736]
wis2downloader to use image built by wis2downloader repository

**Comment by tomkralidis** [comment]
2024-08-20:
- implemented, being tested/docs (@david-i-berry)

**Comment by maaikelimper** [comment]
Dave implemented this in this PR:
https://github.com/wmo-im/wis2box/pull/742

Note that users migrating from existing installation will need migration steps to cover the additional steps added in wis2box-create-config.py in order to use wis2downloader

The download-functionality will no longer work for users running wis2box on Windows.

**Comment by tomkralidis** [comment]
@david-i-berry to verify install on Windows.

**Comment by david-i-berry** [comment]
Completed and merged as part of https://github.com/wmo-im/wis2box/pull/742
