### ISSUE TITLE
wis2box-webapp CSV to BUFR Form does not work

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#738]
I am unable to make wis2box-webapp CSV to BUFR Form work in the latest release of wis2box. I can not proceed to the next step after selecting a file:

![image](https://github.com/user-attachments/assets/b8652dba-6556-43c3-9057-5b01b6cd7949)

**Comment by tomkralidis** [comment]
2024-08-20:
- @RoryPTB is able to reproduce and is investigating

**Comment by RoryPTB** [comment]
Fixed in [PR 57](https://github.com/wmo-im/wis2box-webapp/pull/57), although further testing is desirable.

**Comment by tomkralidis** [comment]
Addressed in https://github.com/wmo-im/wis2box-webapp/pull/57 needs review/merge/test/validate.

**Comment by tomkralidis** [comment]
Fixed/validated.
