### ISSUE TITLE
Running wis2box without ipv6

### ISSUE THREAD

**Issue by gespau** [wmo-im/wis2box#745]
## User story
As an admin, I want to install wis2box on a virtual machine without ipv6 support so that we can run a wis2 node. 

The container `wis2box-ui:latest` does not start because [`/etc/nginx/nginx.conf`](https://github.com/wmo-im/wis2box-ui/blob/main/docker/nginx.conf#L12), which [is copied into the container at build time](https://github.com/wmo-im/wis2box-ui/blob/main/Dockerfile#L32), has an ipv6-specific line. 

The nginx docker image, which is included in `wis2box-ui` image, [checks](https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/10-listen-on-ipv6-by-default.sh#L15-L19) upon starting if ipv6 is available and only if it is available, it adds the according ipv6-specific line (`listen  [::]:80;`). 

#### Proposed solution
We could do something similar to the nginx docker image approach by adding some lines to [our entrypoint script](https://github.com/wmo-im/wis2box-ui/blob/main/docker/entrypoint.sh): 

1. We could either delete the ipv6-specific line (`listen  [::]:80;`) from [nginx.conf](https://github.com/wmo-im/wis2box-ui/blob/main/docker/nginx.conf#L12) and only [add ipv6-specific line](https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/10-listen-on-ipv6-by-default.sh#L62-L63) if ipv6 is available
2. or we could delete the line if ipv6 is available by appending a few lines to [our entrypoint script](https://github.com/wmo-im/wis2box-ui/blob/main/docker/entrypoint.sh)
```
# check if we have ipv6 available
if [ ! -f "/proc/net/if_inet6" ]; then
    # log only if not quieted by variable 
    if [ -z "${NGINX_ENTRYPOINT_QUIET_LOGS:-}" ]; then
        ME=$(basename "$0")
        echo "$ME: info: ipv6 not available
    fi 
    #disable ipv6 on listen sockets
    sed -i '/[::]:80/d' /etc/nginx/nginx.con
fi
```
(nested logging if-statement could be omitted ... 

## Acceptance criteria

- [ ] `python3 wis2box-ctl.py start` runs successfully on machines without ipv6. 

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by maaikelimper** [comment]
@gespau thank you for posting this issue

@tomkralidis wis2box-ui was meant to be proxied via the host, so I don't think this line is required at all inside the container:
https://github.com/wmo-im/wis2box-ui/blob/main/docker/nginx.conf#L12
