### ISSUE TITLE
suppress  "Error response from daemon:" at wis2box start

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#747]
We should suppress these "Error response from daemon:"-lines when wis2box starts. They are not actual errors but they confuse wis2box-users:
```
wis2box_user@wis2box-1-0b7-test-server:~/wis2box$ python3 wis2box-ctl.py start
Error response from daemon: plugin loki:latest already exists
Error response from daemon: plugin already enabled: plugin loki:latest is enabled
```

See
https://github.com/wmo-im/wis2box/blob/main/wis2box-ctl.py#L181-L185

**Comment by gespau** [comment]
alternatively we could have added
```
docker plugin disable loki
docker plugin rm loki
```
to the routine executed by
```
python3 wis2box-ctl.py stop
```
