### ISSUE TITLE
custom csv2bufr json mapping template in plugin configuration

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#758]
Issue reported by Rodrigo from Argentina

Hello Maaike, I hope you are well.
I am contacting you because we are trying to install the version 1.b08 of W2B and we are having issues with using custom templates for csv2bufr.
We don't understand where we need to put the json mapping template:

![image](https://github.com/user-attachments/assets/23b0ca31-1c29-48b3-9391-7488f562df68)

The plugin configuration in the dataset editor does not currently support custom templates.

**Comment by RoryPTB** [comment]
Currently if the plugin is found in the existing dataset, the field is set to that value (`DatasetEditorForm.vue`, `line 1551`):
```javascript
const populatePluginFields = (plugin) => {
            // If plugin exists, populate the fields
            if (plugin) {
                pluginIsNew.value = false;
                pluginFileExtension.value = plugin.fileType;
                pluginName.value = plugin.name;
                pluginTemplate.value = plugin.template;
```
This would mean the dataset was created manually with that plugin and then loaded into the dataset editor. It would be trivial to remove the template value if it doesn't fall in the hard-coded list, however I don't see why we would want to erase this information?

**Comment by maaikelimper** [comment]
Hi Rory, you are correct the user had manually created the the dataset with this plugin, and the dataset-editor correctly displayed the value and I don't think we want to erase this information.

Ideally, the DatasetEditorForm.vue should also let the user select a custom template defined in the wis2box, but I am not sure how to do this. 

@david-i-berry do you have a suggestion how the dataset-editor could work with custom csv2bufr-templates ?

**Comment by david-i-berry** [comment]
pygeoapi process to list templates? we already do something similar in the csv2bufr plugin.

**Comment by maaikelimper** [comment]
OK so resolving this issue requires the completion of 2 PRs:
- [ ] update wis2box-api with new pygeoapi process to list available csv2bufr templates in the wis2box-instance
- [ ] update wis2box-webapp to list templates based on the output of the new process

@david-i-berry this issue is currently assigned to you, is this ok, or should we split the work ?

**Comment by alimand** [comment]
Please see: https://github.com/wmo-im/wis2box-webapp/pull/75

**Comment by maaikelimper** [comment]
implement in latest version of wis2box-webapp
