### ISSUE TITLE
document usage of CSV2BUFR_TEMPLATES in wis2box

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#759]
We are missing documentation for the usage of the environment variables CSV2BUFR_TEMPLATES in wis2box and how this would be used in the plugin definiton:

https://docs.wis2box.wis.wmo.int/en/latest/reference/running/data-pipeline-plugins.html#wis2box-data-csv2bufr-observationdatacsv2bufr

**Comment by tomkralidis** [comment]
2024-11-21: @maaikelimper to address via volume mappings, then document accordingly.
