### ISSUE TITLE
Inconsistency Between INFCOM-3-d08-3-WIS-MANUAL and WIS2 Notification Message Format in wis2box 1.0b8

### ISSUE THREAD

**Issue by alimand** [wmo-im/wis2box#768]
## User story
As a wis2box 1.0b8 user, I want to align the message format with both INFCOM-3-d08-3-WIS-MANUAL and the latest WIS2 Notification Message draft standards so that my messages are correctly forwarded and stored by GB and GC systems without failure due to format validation issues.

INFCOM-3-d08-3-WIS-MANUAL:
![57b67518f0bc771ee323d5916980d96d](https://github.com/user-attachments/assets/01fffddb-29cb-44ba-ac9c-4784497e3af1)

latest WIS2 Notification Message draft standards(https://wmo-im.github.io/wis2-notification-message/standard/wis2-notification-message-DRAFT.html#_1_6_version):
![WechatIMG211](https://github.com/user-attachments/assets/9a183732-6b4a-4a5d-98ac-ec93737ac819)

## Acceptance criteria
- The message format in wis2box 1.0b8 adheres to the INFCOM-3-d08-3-WIS-MANUAL (because user only have Manual to follow) so when they use wis2box 1.0b8, the notification message could be deal with GB or GDC correctly **or** leave wis2box 1.0b8 unchanged but update INFCOM-3-d08-3-WIS-MANUAL, do not use version and use conformsTo.
- A solution is provided to resolve the inconsistency between INFCOM-3-d08-3-WIS-MANUAL (where version is mandatory) and the WIS2 draft standard (where version is deprecated).
- Ensure messages are correctly validated and accepted by GB and GC systems.

## Definition of done
- unit/functional tests added/updated
- documentation updated

**Comment by maaikelimper** [comment]
@tomkralidis I thought we already aligned with the WIS2 Notification Message standard in the current version of wis2box, what did we miss?
