### ISSUE TITLE
error pyoscar get_station_report_summary when retrieving 0-76-0-5208707000000007

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#773]
Hi Tom,

When getting metadata station 0-76-0-5208707000000007 we encounter an error originating in pyoscar, could you have look?

wis2box metadata station get 0-76-0-5208707000000007
```
Traceback (most recent call last):
  File "/usr/local/bin/wis2box", line 33, in <module>
    sys.exit(load_entry_point('wis2box', 'console_scripts', 'wis2box')())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/wis2box/metadata/station.py", line 470, in get
    station = client.get_station_report(wsi, format_='XML', summary=True)
  File "/usr/local/lib/python3.10/dist-packages/pyoscar/__init__.py", line 226, in get_station_report
    return self.get_station_report_summary(response)
  File "/usr/local/lib/python3.10/dist-packages/pyoscar/__init__.py", line 257, in get_station_report_summary
    station, '//wmdr:ObservingFacility/gml:identifier').split(',')[0]  # noqa
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by tomkralidis** [comment]
Reproduced locally via:

```bash
pyoscar station "0-76-0-3170206000000036" -s XML
```

Interestingly enough, `pyoscar station "0-76-0-3170206000000036" -s` works fine (however we are explicitly asking for the WMDR XML output in wis2box).  I've reached out to OSCAR/Surface and will report back on their response.  cc @david-i-berry

**Comment by david-i-berry** [comment]
WIS2box, via pyoscar, accesses the following link:

https://[oscar.wmo.int/oai/provider?verb=GetRecord&metadataPrefix=wmdr&identifier=0-76-0-3170206000000036](https://oscar.wmo.int/oai/provider?verb=GetRecord&metadataPrefix=wmdr&identifier=0-76-0-3170206000000036)

This works and returns the XML via the browser.

**Comment by david-i-berry** [comment]
the following command also works:

` pyoscar station "0-76-0-3170206000000036" --format=XML --env=prod`

and returns the XML as expected.

**Comment by david-i-berry** [comment]
A bit more investigation:

```python
import json
from pyoscar import OSCARClient
client = OSCARClient(env='prod')
station = client.get_station_report("0-76-0-3170206000000036", format_='XML', summary=True)
print(json.dumps(station, indent = 4))
```

gives  the following output:

```json
{
    "station_name": "UBERLANDIA",
    "wigos_station_identifier": "0-76-0-3170206000000036",
    "facility_type": "landFixed",
    "wmo_region": "southAmerica",
    "territory_name": "BRA",
    "latitude": -18.916944,
    "longitude": -48.255556,
    "elevation": 874.8,
    "barometer_height": 870.5
}
```

This is the line from the wis2box-api where we fetch from OSCAR:

https://github.com/wmo-im/wis2box-api/blob/b351aa45fb67e69138c210b7b93158c09d459d32/wis2box_api/plugins/process/oscar2feature.py#L112

The error either occurs after here or there are network problems.

**Comment by maaikelimper** [comment]
José reported that the problem fixed itself after one day. This was the second day station where Brazil updated the primary wigos-id during the training, failed to import it into wis2box, then repeat the import one day later and it works.

We suspect that there is something about the way that OSCAR/Surface works, whereby an update does not immediately translate into the station being available for import into the wis2box, but can be imported one day later ...

**Comment by maaikelimper** [comment]
I don't think this an issue we can fix in wis2box, closing
