### ISSUE TITLE
wis2box-webapp dataset editor: auto-lowercase centre-id

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#804]
Hi Peiwen,

During the recent training in Casablanca one participant managed to create a dataset with an upper-case centre-id (DJ-ANM instead of dj-anm) 

This resulted in an invalid metadata record being published.

In order to avoid the user incorrectly providing an upper-case centre-id, can you please ensure that the dataset-editor in wis2box-webapp automatically formats the centre-id provided by the user in lowercase ?

![image](https://github.com/user-attachments/assets/c81a9be3-f9d3-4bd5-8b71-a31eeca88cbb)

**Comment by alimand** [comment]
Updated Dec 2:
Please see: https://github.com/wmo-im/wis2box-webapp/pull/74

**Comment by maaikelimper** [comment]
fixed in latest version of wis2box-webapp
