### ISSUE TITLE
allow user to specify BUFR_ORIGINATING_CENTRE and BUFR_SUBORIGNATING_CENTRE dynamically per dataset in wis2box

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#810]
Based on the Dave's comment https://github.com/wmo-im/wis2box/issues/778#issuecomment-2504026601

wis2box dynamically update the mapping here: https://github.com/wmo-im/wis2box-api/blob/67e423a3fef3ebc089d10203f81573a099918da1/wis2box_api/plugins/process/csv2bufr.py#L175

The plugin could access these values from additional properties stored in the 'wis2box'-block of the dataset-record.

We need to implement and/or document how to add these properties to the dataset-record

**Comment by tomkralidis** [comment]
Closing/wontfix
