### ISSUE TITLE
add demo data bundle

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#84]
Create a bundle (1000s of CSVs) of the Malawi data:
- across/over 7-14 days
- across the maximum number of stations possible

The bundle should be posted to WMO Confluence as a zip file with:
- CSVs of data
- a station list formatted as per the test examples at https://github.com/wmo-im/wis2box/blob/main/tests/data/metadata/station/station_list.csv

**Comment by tomkralidis** [comment]
Thanks @chenxiaoxia2019.  Can you add to the zip a file called `station_list.csv` that is formatted like https://github.com/wmo-im/wis2box/blob/main/tests/data/metadata/station/station_list.csv with the relevant stations in the zip?

**Comment by tomkralidis** [comment]
In addition, there are some files per below where the WSI in the filename is in lowercase but should be UPPERCASE to match the official WSI:

- `WIGOS_0-454-2-awsmlomba_*` should be `0-454-2-AWSMLOMBA`
- `WIGOS_0-454-2-awsnamitambo_*` should be `0-454-2-AWSNAMITAMBO`

**Comment by chenxiaoxia2019** [comment]
@tomkralidis The WSI of these two stations in the filename was not set correctly. But now they are sending with the correct WSI using Uppercase. So far, the WSI in the filename is not from the OSCAR, but to follow our list we prepared for Campbell. We are also contacting a Malawi colleague who takes care of OSCAR to correct another two wrong WSI. 

- WIGOS_0-454-2-awsmlomba_* (one file: WIGOS_0-454-2-awsmlomba_2022-01-17T1256)
- WIGOS_0-454-2-awsnamitambo_* (from 2022-01-25 to 2022-01-26T0755)

P.S Another two stations needed to be corrected from OSCAR.
- 0-454-2-AWNNAMBUMA -->0-454-2-AWSNAMBUMA 
- 0-454-2-a10343014 -->0-454-2-AWSMHUJU

**Comment by chenxiaoxia2019** [comment]
> Thanks @chenxiaoxia2019. Can you add to the zip a file called `station_list.csv` that is formatted like https://github.com/wmo-im/wis2box/blob/main/tests/data/metadata/station/station_list.csv with the relevant stations in the zip?

@tomkralidis Do we only need the list for the currently available stations?

**Comment by chenxiaoxia2019** [comment]
> In addition, there are some files per below where the WSI in the filename is in lowercase but should be UPPERCASE to match the official WSI:
> 
> * `WIGOS_0-454-2-awsmlomba_*` should be `WIGOS_0-454-2-AWSMLOMBA_*`
> * `WIGOS_0-454-2-awsnamitambo_*` should be `WIGOS_0-454-2-AWSNAMITAMBO_*`

https://wmo-teams.atlassian.net/wiki/spaces/WIS2/pages/302907405/WIS+2.0+in+a+box
I added the currently available station list here.

**Comment by chenxiaoxia2019** [comment]
> Thanks @chenxiaoxia2019. Can you add to the zip a file called `station_list.csv` that is formatted like https://github.com/wmo-im/wis2box/blob/main/tests/data/metadata/station/station_list.csv with the relevant stations in the zip?

https://wmo-teams.atlassian.net/wiki/spaces/WIS2/pages/302907405/WIS+2.0+in+a+box
I added the currently available station list here.

**Comment by tomkralidis** [comment]
Thanks @chenxiaoxia2019 

- correct, only stations that are in the data bundle
- can you place the station list CSV file in the data bundle zipfile?  Then anyone setting up a demo only has to download the bundle which will have both the station list and data

**Comment by chenxiaoxia2019** [comment]
@tomkralidis The ZipFile has been updated with the station_list.csv

**Comment by tomkralidis** [comment]
Thanks @chenxiaoxia2019.  I've made some minor touchups (file rename to `Malawi_SYNOP_20220216.zip`) and uploaded a new zip.  As well, following our discussion at today's standup, from `stations_list.csv`, I removed the station name field, and renamed the WSI field to `wigos_station_identifier` because wis2box is tied to that column name.

Let me know if this is okay.
