### ISSUE TITLE
Node local copy of GTS data

### ISSUE THREAD

**Issue by petersilva** [wmo-im/wis2box#91]
## User story
As someone operating a mission-critical service, I need my operations to work if I lose internet, or access to a particular cloud or cloud instance. I need my on-prem implementation to have a copy of the entire world's data, as is done for all NC's that operate a traditional GTS switch. So there should be something on wis2node that can subscribe to data from around the world, either selecting all of it, or limiting selection using MQP to a specific area relevant to a given centre.

Countries want a degree of self-determination, not being subject to the availability of a single other country's services. It should be possible to obtain data from a second country in the case the usual upstream connection is in difficulty.

## Acceptance criteria

- [ ] ability to deploy wis2box on-prem.
- [ ] Have local copies of entire GTS in real-time, on that on-prem instance (given sufficient internet connection.)
- [ ] Restrict above real-time feed to subset of GTS bulletins downloaded to a geographical subset.
- [ ] users should be able include some NWP products, in addition to GTS ones, and GTS ones should not be queued behind the NWP ones.
- [ ] warning data latency should be very low.
- [ ] Able to connect to a second upstream source to withstand failure.
- [ ] reasonable latency and bandwidth efficiency.
- [ ] ability to serve local applications with the data.

## Definition of done

- [ ] unit/functional tests added/updated
- [ ] documentation updated
- [ ] live demonstration provided

**Comment by tomkralidis** [comment]
Realized by wis2downloader as part of next release.
